// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/capture.dart';
import 'api/ffmpeg.dart';
import 'api/logger.dart';
import 'api/module_api.dart';
import 'api/module_loader.dart';
import 'api/module_manager.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1212724051;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_slime_works',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiFfmpegFFmpegManagerGenerateThumbnail({
    required FFmpegManager that,
    required String videoUrl,
    required String outputPath,
  });

  Future<VideoMetadata> crateApiFfmpegFFmpegManagerGetMetadata({
    required FFmpegManager that,
    required String videoPath,
  });

  Future<void> crateApiFfmpegFFmpegManagerInitialize({
    required FFmpegManager that,
  });

  Future<FFmpegManager> crateApiFfmpegFFmpegManagerNew({
    required FFmpegConfig config,
  });

  Future<void> crateApiModuleLoaderCaptureProxyModuleClearData({
    required String installDir,
  });

  Future<List<String>> crateApiModuleLoaderCaptureProxyModuleGetVideos({
    required String installDir,
  });

  Future<void> crateApiModuleLoaderCaptureProxyModuleInstallCertificate({
    required String password,
    required String installDir,
  });

  Future<bool> crateApiModuleLoaderCaptureProxyModuleIsCertificateInstalled({
    required String installDir,
  });

  Future<bool> crateApiModuleLoaderCaptureProxyModuleIsRunning({
    required String installDir,
  });

  Future<String> crateApiModuleLoaderCaptureProxyModuleStart({
    required int port,
    required String installDir,
  });

  Future<String> crateApiModuleLoaderCaptureProxyModuleStop({
    required String installDir,
  });

  Future<List<ModuleStatus>> crateApiModuleApiCheckAllModulesStatus({
    required String installDir,
    required String captureProxyVersion,
    required String captureProxyWindowsUrl,
    required String captureProxyMacosUrl,
    required String ffmpegVersion,
    required String ffmpegWindowsUrl,
    required String ffmpegMacosUrl,
  });

  bool crateApiModuleApiCheckModuleNeedsUpdate({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String currentVersion,
    required String windowsUrl,
    required String macosUrl,
    required String fileName,
  });

  int crateApiCaptureCleanupLoggerOldFiles({required int daysToKeep});

  Future<BigInt> crateApiLoggerCleanupOldLogs({required int daysToKeep});

  void crateApiCaptureClearCapturedData({String? installDir});

  Future<String> crateApiModuleApiDownloadCaptureProxyModule({
    required String installDir,
    required String version,
    required String windowsUrl,
    required String macosUrl,
  });

  Future<String> crateApiModuleLoaderDownloadCaptureProxyModule({
    required String windowsUrl,
    required String macosUrl,
    required String installDir,
  });

  Future<String> crateApiModuleApiDownloadFfmpegModule({
    required String installDir,
    required String version,
    required String windowsUrl,
    required String macosUrl,
  });

  Future<String> crateApiModuleApiDownloadModule({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String version,
    required String windowsUrl,
    required String macosUrl,
    required String fileName,
  });

  Future<String> crateApiFfmpegGenerateVideoThumbnail({
    required String videoUrl,
    required String cacheDir,
  });

  CaptureStats? crateApiCaptureGetCaptureStats({String? installDir});

  List<String> crateApiCaptureGetCapturedImages({String? installDir});

  List<String> crateApiCaptureGetCapturedJavascript({String? installDir});

  List<String> crateApiCaptureGetCapturedJson({String? installDir});

  List<String> crateApiCaptureGetCapturedVideos({String? installDir});

  Future<String> crateApiFfmpegGetFfmpegVersion({required String installDir});

  String? crateApiModuleApiGetInstalledModuleVersion({
    required String installDir,
    required String moduleName,
  });

  Future<String?> crateApiLoggerGetLogDir();

  String? crateApiCaptureGetLoggerDirectory();

  String crateApiModuleApiGetModuleFilePath({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String fileName,
  });

  Future<VideoMetadata> crateApiFfmpegGetVideoMetadata({
    required String videoPath,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiLoggerInitLogger({required String installDir});

  Future<String> crateApiFfmpegInitializeFfmpeg({
    required String windowsUrl,
    required String macosUrl,
    required String installDir,
  });

  String crateApiCaptureInitializeLogger({String? installDir});

  String crateApiCaptureInstallCaCertificate({
    required String password,
    String? installDir,
  });

  bool crateApiCaptureIsCaCertificateInstalled({String? installDir});

  Future<bool> crateApiModuleLoaderIsCaptureProxyDownloaded({
    required String installDir,
  });

  Future<bool> crateApiFfmpegIsFfmpegInstalled({required String installDir});

  bool crateApiModuleApiIsModuleInstalled({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String fileName,
  });

  bool crateApiCaptureIsProxyRunning({String? installDir});

  bool crateApiCaptureIsRunningAsAdministrator();

  Future<void> crateApiLoggerLogDebug({required String message});

  Future<void> crateApiLoggerLogError({required String message});

  Future<void> crateApiLoggerLogInfo({required String message});

  Future<void> crateApiLoggerLogWarn({required String message});

  String crateApiCaptureStartCaptureProxy({
    required int port,
    String? installDir,
  });

  String crateApiCaptureStopCaptureProxy({String? installDir});

  void crateApiCaptureWriteLogError({required String message});

  void crateApiCaptureWriteLogInfo({required String message});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FFmpegManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FFmpegManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FFmpegManagerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiFfmpegFFmpegManagerGenerateThumbnail({
    required FFmpegManager that,
    required String videoUrl,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
            that,
            serializer,
          );
          sse_encode_String(videoUrl, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegFFmpegManagerGenerateThumbnailConstMeta,
        argValues: [that, videoUrl, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegFFmpegManagerGenerateThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "FFmpegManager_generate_thumbnail",
        argNames: ["that", "videoUrl", "outputPath"],
      );

  @override
  Future<VideoMetadata> crateApiFfmpegFFmpegManagerGetMetadata({
    required FFmpegManager that,
    required String videoPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
            that,
            serializer,
          );
          sse_encode_String(videoPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_metadata,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegFFmpegManagerGetMetadataConstMeta,
        argValues: [that, videoPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegFFmpegManagerGetMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "FFmpegManager_get_metadata",
        argNames: ["that", "videoPath"],
      );

  @override
  Future<void> crateApiFfmpegFFmpegManagerInitialize({
    required FFmpegManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegFFmpegManagerInitializeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegFFmpegManagerInitializeConstMeta =>
      const TaskConstMeta(
        debugName: "FFmpegManager_initialize",
        argNames: ["that"],
      );

  @override
  Future<FFmpegManager> crateApiFfmpegFFmpegManagerNew({
    required FFmpegConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_f_fmpeg_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFfmpegFFmpegManagerNewConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegFFmpegManagerNewConstMeta =>
      const TaskConstMeta(debugName: "FFmpegManager_new", argNames: ["config"]);

  @override
  Future<void> crateApiModuleLoaderCaptureProxyModuleClearData({
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleLoaderCaptureProxyModuleClearDataConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderCaptureProxyModuleClearDataConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_clear_data",
        argNames: ["installDir"],
      );

  @override
  Future<List<String>> crateApiModuleLoaderCaptureProxyModuleGetVideos({
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleLoaderCaptureProxyModuleGetVideosConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderCaptureProxyModuleGetVideosConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_get_videos",
        argNames: ["installDir"],
      );

  @override
  Future<void> crateApiModuleLoaderCaptureProxyModuleInstallCertificate({
    required String password,
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModuleLoaderCaptureProxyModuleInstallCertificateConstMeta,
        argValues: [password, installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModuleLoaderCaptureProxyModuleInstallCertificateConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_install_certificate",
        argNames: ["password", "installDir"],
      );

  @override
  Future<bool> crateApiModuleLoaderCaptureProxyModuleIsCertificateInstalled({
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModuleLoaderCaptureProxyModuleIsCertificateInstalledConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModuleLoaderCaptureProxyModuleIsCertificateInstalledConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_is_certificate_installed",
        argNames: ["installDir"],
      );

  @override
  Future<bool> crateApiModuleLoaderCaptureProxyModuleIsRunning({
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleLoaderCaptureProxyModuleIsRunningConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderCaptureProxyModuleIsRunningConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_is_running",
        argNames: ["installDir"],
      );

  @override
  Future<String> crateApiModuleLoaderCaptureProxyModuleStart({
    required int port,
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleLoaderCaptureProxyModuleStartConstMeta,
        argValues: [port, installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderCaptureProxyModuleStartConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_start",
        argNames: ["port", "installDir"],
      );

  @override
  Future<String> crateApiModuleLoaderCaptureProxyModuleStop({
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleLoaderCaptureProxyModuleStopConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderCaptureProxyModuleStopConstMeta =>
      const TaskConstMeta(
        debugName: "capture_proxy_module_stop",
        argNames: ["installDir"],
      );

  @override
  Future<List<ModuleStatus>> crateApiModuleApiCheckAllModulesStatus({
    required String installDir,
    required String captureProxyVersion,
    required String captureProxyWindowsUrl,
    required String captureProxyMacosUrl,
    required String ffmpegVersion,
    required String ffmpegWindowsUrl,
    required String ffmpegMacosUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(captureProxyVersion, serializer);
          sse_encode_String(captureProxyWindowsUrl, serializer);
          sse_encode_String(captureProxyMacosUrl, serializer);
          sse_encode_String(ffmpegVersion, serializer);
          sse_encode_String(ffmpegWindowsUrl, serializer);
          sse_encode_String(ffmpegMacosUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_module_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModuleApiCheckAllModulesStatusConstMeta,
        argValues: [
          installDir,
          captureProxyVersion,
          captureProxyWindowsUrl,
          captureProxyMacosUrl,
          ffmpegVersion,
          ffmpegWindowsUrl,
          ffmpegMacosUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiCheckAllModulesStatusConstMeta =>
      const TaskConstMeta(
        debugName: "check_all_modules_status",
        argNames: [
          "installDir",
          "captureProxyVersion",
          "captureProxyWindowsUrl",
          "captureProxyMacosUrl",
          "ffmpegVersion",
          "ffmpegWindowsUrl",
          "ffmpegMacosUrl",
        ],
      );

  @override
  bool crateApiModuleApiCheckModuleNeedsUpdate({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String currentVersion,
    required String windowsUrl,
    required String macosUrl,
    required String fileName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(moduleName, serializer);
          sse_encode_module_type(moduleType, serializer);
          sse_encode_String(currentVersion, serializer);
          sse_encode_String(windowsUrl, serializer);
          sse_encode_String(macosUrl, serializer);
          sse_encode_String(fileName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModuleApiCheckModuleNeedsUpdateConstMeta,
        argValues: [
          installDir,
          moduleName,
          moduleType,
          currentVersion,
          windowsUrl,
          macosUrl,
          fileName,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiCheckModuleNeedsUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "check_module_needs_update",
        argNames: [
          "installDir",
          "moduleName",
          "moduleType",
          "currentVersion",
          "windowsUrl",
          "macosUrl",
          "fileName",
        ],
      );

  @override
  int crateApiCaptureCleanupLoggerOldFiles({required int daysToKeep}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(daysToKeep, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCaptureCleanupLoggerOldFilesConstMeta,
        argValues: [daysToKeep],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureCleanupLoggerOldFilesConstMeta =>
      const TaskConstMeta(
        debugName: "cleanup_logger_old_files",
        argNames: ["daysToKeep"],
      );

  @override
  Future<BigInt> crateApiLoggerCleanupOldLogs({required int daysToKeep}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(daysToKeep, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoggerCleanupOldLogsConstMeta,
        argValues: [daysToKeep],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerCleanupOldLogsConstMeta =>
      const TaskConstMeta(
        debugName: "cleanup_old_logs",
        argNames: ["daysToKeep"],
      );

  @override
  void crateApiCaptureClearCapturedData({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCaptureClearCapturedDataConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureClearCapturedDataConstMeta =>
      const TaskConstMeta(
        debugName: "clear_captured_data",
        argNames: ["installDir"],
      );

  @override
  Future<String> crateApiModuleApiDownloadCaptureProxyModule({
    required String installDir,
    required String version,
    required String windowsUrl,
    required String macosUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(version, serializer);
          sse_encode_String(windowsUrl, serializer);
          sse_encode_String(macosUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleApiDownloadCaptureProxyModuleConstMeta,
        argValues: [installDir, version, windowsUrl, macosUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiDownloadCaptureProxyModuleConstMeta =>
      const TaskConstMeta(
        debugName: "download_capture_proxy_module",
        argNames: ["installDir", "version", "windowsUrl", "macosUrl"],
      );

  @override
  Future<String> crateApiModuleLoaderDownloadCaptureProxyModule({
    required String windowsUrl,
    required String macosUrl,
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowsUrl, serializer);
          sse_encode_String(macosUrl, serializer);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleLoaderDownloadCaptureProxyModuleConstMeta,
        argValues: [windowsUrl, macosUrl, installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderDownloadCaptureProxyModuleConstMeta =>
      const TaskConstMeta(
        debugName: "download_capture_proxy_module",
        argNames: ["windowsUrl", "macosUrl", "installDir"],
      );

  @override
  Future<String> crateApiModuleApiDownloadFfmpegModule({
    required String installDir,
    required String version,
    required String windowsUrl,
    required String macosUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(version, serializer);
          sse_encode_String(windowsUrl, serializer);
          sse_encode_String(macosUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleApiDownloadFfmpegModuleConstMeta,
        argValues: [installDir, version, windowsUrl, macosUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiDownloadFfmpegModuleConstMeta =>
      const TaskConstMeta(
        debugName: "download_ffmpeg_module",
        argNames: ["installDir", "version", "windowsUrl", "macosUrl"],
      );

  @override
  Future<String> crateApiModuleApiDownloadModule({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String version,
    required String windowsUrl,
    required String macosUrl,
    required String fileName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(moduleName, serializer);
          sse_encode_module_type(moduleType, serializer);
          sse_encode_String(version, serializer);
          sse_encode_String(windowsUrl, serializer);
          sse_encode_String(macosUrl, serializer);
          sse_encode_String(fileName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModuleApiDownloadModuleConstMeta,
        argValues: [
          installDir,
          moduleName,
          moduleType,
          version,
          windowsUrl,
          macosUrl,
          fileName,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiDownloadModuleConstMeta =>
      const TaskConstMeta(
        debugName: "download_module",
        argNames: [
          "installDir",
          "moduleName",
          "moduleType",
          "version",
          "windowsUrl",
          "macosUrl",
          "fileName",
        ],
      );

  @override
  Future<String> crateApiFfmpegGenerateVideoThumbnail({
    required String videoUrl,
    required String cacheDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(videoUrl, serializer);
          sse_encode_String(cacheDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegGenerateVideoThumbnailConstMeta,
        argValues: [videoUrl, cacheDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegGenerateVideoThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "generate_video_thumbnail",
        argNames: ["videoUrl", "cacheDir"],
      );

  @override
  CaptureStats? crateApiCaptureGetCaptureStats({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_capture_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureGetCaptureStatsConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureGetCaptureStatsConstMeta =>
      const TaskConstMeta(
        debugName: "get_capture_stats",
        argNames: ["installDir"],
      );

  @override
  List<String> crateApiCaptureGetCapturedImages({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureGetCapturedImagesConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureGetCapturedImagesConstMeta =>
      const TaskConstMeta(
        debugName: "get_captured_images",
        argNames: ["installDir"],
      );

  @override
  List<String> crateApiCaptureGetCapturedJavascript({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureGetCapturedJavascriptConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureGetCapturedJavascriptConstMeta =>
      const TaskConstMeta(
        debugName: "get_captured_javascript",
        argNames: ["installDir"],
      );

  @override
  List<String> crateApiCaptureGetCapturedJson({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureGetCapturedJsonConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureGetCapturedJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_captured_json",
        argNames: ["installDir"],
      );

  @override
  List<String> crateApiCaptureGetCapturedVideos({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureGetCapturedVideosConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureGetCapturedVideosConstMeta =>
      const TaskConstMeta(
        debugName: "get_captured_videos",
        argNames: ["installDir"],
      );

  @override
  Future<String> crateApiFfmpegGetFfmpegVersion({required String installDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegGetFfmpegVersionConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegGetFfmpegVersionConstMeta =>
      const TaskConstMeta(
        debugName: "get_ffmpeg_version",
        argNames: ["installDir"],
      );

  @override
  String? crateApiModuleApiGetInstalledModuleVersion({
    required String installDir,
    required String moduleName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(moduleName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModuleApiGetInstalledModuleVersionConstMeta,
        argValues: [installDir, moduleName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetInstalledModuleVersionConstMeta =>
      const TaskConstMeta(
        debugName: "get_installed_module_version",
        argNames: ["installDir", "moduleName"],
      );

  @override
  Future<String?> crateApiLoggerGetLogDir() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerGetLogDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerGetLogDirConstMeta =>
      const TaskConstMeta(debugName: "get_log_dir", argNames: []);

  @override
  String? crateApiCaptureGetLoggerDirectory() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureGetLoggerDirectoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureGetLoggerDirectoryConstMeta =>
      const TaskConstMeta(debugName: "get_logger_directory", argNames: []);

  @override
  String crateApiModuleApiGetModuleFilePath({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String fileName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(moduleName, serializer);
          sse_encode_module_type(moduleType, serializer);
          sse_encode_String(fileName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModuleApiGetModuleFilePathConstMeta,
        argValues: [installDir, moduleName, moduleType, fileName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetModuleFilePathConstMeta =>
      const TaskConstMeta(
        debugName: "get_module_file_path",
        argNames: ["installDir", "moduleName", "moduleType", "fileName"],
      );

  @override
  Future<VideoMetadata> crateApiFfmpegGetVideoMetadata({
    required String videoPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(videoPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_metadata,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegGetVideoMetadataConstMeta,
        argValues: [videoPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegGetVideoMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "get_video_metadata",
        argNames: ["videoPath"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiLoggerInitLogger({required String installDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoggerInitLoggerConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerInitLoggerConstMeta =>
      const TaskConstMeta(debugName: "init_logger", argNames: ["installDir"]);

  @override
  Future<String> crateApiFfmpegInitializeFfmpeg({
    required String windowsUrl,
    required String macosUrl,
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowsUrl, serializer);
          sse_encode_String(macosUrl, serializer);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFfmpegInitializeFfmpegConstMeta,
        argValues: [windowsUrl, macosUrl, installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegInitializeFfmpegConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_ffmpeg",
        argNames: ["windowsUrl", "macosUrl", "installDir"],
      );

  @override
  String crateApiCaptureInitializeLogger({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCaptureInitializeLoggerConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureInitializeLoggerConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_logger",
        argNames: ["installDir"],
      );

  @override
  String crateApiCaptureInstallCaCertificate({
    required String password,
    String? installDir,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCaptureInstallCaCertificateConstMeta,
        argValues: [password, installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureInstallCaCertificateConstMeta =>
      const TaskConstMeta(
        debugName: "install_ca_certificate",
        argNames: ["password", "installDir"],
      );

  @override
  bool crateApiCaptureIsCaCertificateInstalled({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureIsCaCertificateInstalledConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureIsCaCertificateInstalledConstMeta =>
      const TaskConstMeta(
        debugName: "is_ca_certificate_installed",
        argNames: ["installDir"],
      );

  @override
  Future<bool> crateApiModuleLoaderIsCaptureProxyDownloaded({
    required String installDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModuleLoaderIsCaptureProxyDownloadedConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleLoaderIsCaptureProxyDownloadedConstMeta =>
      const TaskConstMeta(
        debugName: "is_capture_proxy_downloaded",
        argNames: ["installDir"],
      );

  @override
  Future<bool> crateApiFfmpegIsFfmpegInstalled({required String installDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFfmpegIsFfmpegInstalledConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegIsFfmpegInstalledConstMeta =>
      const TaskConstMeta(
        debugName: "is_ffmpeg_installed",
        argNames: ["installDir"],
      );

  @override
  bool crateApiModuleApiIsModuleInstalled({
    required String installDir,
    required String moduleName,
    required ModuleType moduleType,
    required String fileName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(installDir, serializer);
          sse_encode_String(moduleName, serializer);
          sse_encode_module_type(moduleType, serializer);
          sse_encode_String(fileName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModuleApiIsModuleInstalledConstMeta,
        argValues: [installDir, moduleName, moduleType, fileName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiIsModuleInstalledConstMeta =>
      const TaskConstMeta(
        debugName: "is_module_installed",
        argNames: ["installDir", "moduleName", "moduleType", "fileName"],
      );

  @override
  bool crateApiCaptureIsProxyRunning({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureIsProxyRunningConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureIsProxyRunningConstMeta =>
      const TaskConstMeta(
        debugName: "is_proxy_running",
        argNames: ["installDir"],
      );

  @override
  bool crateApiCaptureIsRunningAsAdministrator() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureIsRunningAsAdministratorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureIsRunningAsAdministratorConstMeta =>
      const TaskConstMeta(
        debugName: "is_running_as_administrator",
        argNames: [],
      );

  @override
  Future<void> crateApiLoggerLogDebug({required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerLogDebugConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerLogDebugConstMeta =>
      const TaskConstMeta(debugName: "log_debug", argNames: ["message"]);

  @override
  Future<void> crateApiLoggerLogError({required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerLogErrorConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerLogErrorConstMeta =>
      const TaskConstMeta(debugName: "log_error", argNames: ["message"]);

  @override
  Future<void> crateApiLoggerLogInfo({required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerLogInfoConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerLogInfoConstMeta =>
      const TaskConstMeta(debugName: "log_info", argNames: ["message"]);

  @override
  Future<void> crateApiLoggerLogWarn({required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoggerLogWarnConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggerLogWarnConstMeta =>
      const TaskConstMeta(debugName: "log_warn", argNames: ["message"]);

  @override
  String crateApiCaptureStartCaptureProxy({
    required int port,
    String? installDir,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCaptureStartCaptureProxyConstMeta,
        argValues: [port, installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureStartCaptureProxyConstMeta =>
      const TaskConstMeta(
        debugName: "start_capture_proxy",
        argNames: ["port", "installDir"],
      );

  @override
  String crateApiCaptureStopCaptureProxy({String? installDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(installDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 50)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCaptureStopCaptureProxyConstMeta,
        argValues: [installDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureStopCaptureProxyConstMeta =>
      const TaskConstMeta(
        debugName: "stop_capture_proxy",
        argNames: ["installDir"],
      );

  @override
  void crateApiCaptureWriteLogError({required String message}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 51)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureWriteLogErrorConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureWriteLogErrorConstMeta =>
      const TaskConstMeta(debugName: "write_log_error", argNames: ["message"]);

  @override
  void crateApiCaptureWriteLogInfo({required String message}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 52)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureWriteLogInfoConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureWriteLogInfoConstMeta =>
      const TaskConstMeta(debugName: "write_log_info", argNames: ["message"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FFmpegManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FFmpegManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager;

  @protected
  FFmpegManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FFmpegManager
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FFmpegManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FFmpegManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CaptureStats dco_decode_box_autoadd_capture_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_capture_stats(raw);
  }

  @protected
  FFmpegConfig dco_decode_box_autoadd_f_fmpeg_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_f_fmpeg_config(raw);
  }

  @protected
  CaptureProxyModule dco_decode_capture_proxy_module(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return CaptureProxyModule();
  }

  @protected
  CaptureStats dco_decode_capture_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CaptureStats(
      total: dco_decode_i_32(arr[0]),
      videos: dco_decode_i_32(arr[1]),
      images: dco_decode_i_32(arr[2]),
      json: dco_decode_i_32(arr[3]),
      javascript: dco_decode_i_32(arr[4]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FFmpegConfig dco_decode_f_fmpeg_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FFmpegConfig(
      windowsUrl: dco_decode_String(arr[0]),
      macosUrl: dco_decode_String(arr[1]),
      installDir: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ModuleStatus> dco_decode_list_module_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_module_status).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ModuleStatus dco_decode_module_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ModuleStatus(
      name: dco_decode_String(arr[0]),
      installed: dco_decode_bool(arr[1]),
      currentVersion: dco_decode_opt_String(arr[2]),
      needsUpdate: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ModuleType dco_decode_module_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ModuleType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CaptureStats? dco_decode_opt_box_autoadd_capture_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_capture_stats(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoMetadata dco_decode_video_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VideoMetadata(
      duration: dco_decode_f_64(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      frameRate: dco_decode_f_64(arr[3]),
      bitRate: dco_decode_u_64(arr[4]),
      codec: dco_decode_String(arr[5]),
      fileSize: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  FFmpegManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FFmpegManager
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FFmpegManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FFmpegManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FFmpegManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CaptureStats sse_decode_box_autoadd_capture_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_capture_stats(deserializer));
  }

  @protected
  FFmpegConfig sse_decode_box_autoadd_f_fmpeg_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_fmpeg_config(deserializer));
  }

  @protected
  CaptureProxyModule sse_decode_capture_proxy_module(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CaptureProxyModule();
  }

  @protected
  CaptureStats sse_decode_capture_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_32(deserializer);
    var var_videos = sse_decode_i_32(deserializer);
    var var_images = sse_decode_i_32(deserializer);
    var var_json = sse_decode_i_32(deserializer);
    var var_javascript = sse_decode_i_32(deserializer);
    return CaptureStats(
      total: var_total,
      videos: var_videos,
      images: var_images,
      json: var_json,
      javascript: var_javascript,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FFmpegConfig sse_decode_f_fmpeg_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_windowsUrl = sse_decode_String(deserializer);
    var var_macosUrl = sse_decode_String(deserializer);
    var var_installDir = sse_decode_String(deserializer);
    return FFmpegConfig(
      windowsUrl: var_windowsUrl,
      macosUrl: var_macosUrl,
      installDir: var_installDir,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModuleStatus> sse_decode_list_module_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModuleStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_module_status(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ModuleStatus sse_decode_module_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_installed = sse_decode_bool(deserializer);
    var var_currentVersion = sse_decode_opt_String(deserializer);
    var var_needsUpdate = sse_decode_bool(deserializer);
    return ModuleStatus(
      name: var_name,
      installed: var_installed,
      currentVersion: var_currentVersion,
      needsUpdate: var_needsUpdate,
    );
  }

  @protected
  ModuleType sse_decode_module_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ModuleType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CaptureStats? sse_decode_opt_box_autoadd_capture_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_capture_stats(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoMetadata sse_decode_video_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_duration = sse_decode_f_64(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_frameRate = sse_decode_f_64(deserializer);
    var var_bitRate = sse_decode_u_64(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    return VideoMetadata(
      duration: var_duration,
      width: var_width,
      height: var_height,
      frameRate: var_frameRate,
      bitRate: var_bitRate,
      codec: var_codec,
      fileSize: var_fileSize,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    FFmpegManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FFmpegManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    FFmpegManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FFmpegManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    FFmpegManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FFmpegManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFFmpegManager(
    FFmpegManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FFmpegManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_capture_stats(
    CaptureStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_capture_stats(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_fmpeg_config(
    FFmpegConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_fmpeg_config(self, serializer);
  }

  @protected
  void sse_encode_capture_proxy_module(
    CaptureProxyModule self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_capture_stats(CaptureStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.videos, serializer);
    sse_encode_i_32(self.images, serializer);
    sse_encode_i_32(self.json, serializer);
    sse_encode_i_32(self.javascript, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_f_fmpeg_config(FFmpegConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.windowsUrl, serializer);
    sse_encode_String(self.macosUrl, serializer);
    sse_encode_String(self.installDir, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_module_status(
    List<ModuleStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_module_status(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_module_status(ModuleStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.installed, serializer);
    sse_encode_opt_String(self.currentVersion, serializer);
    sse_encode_bool(self.needsUpdate, serializer);
  }

  @protected
  void sse_encode_module_type(ModuleType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_capture_stats(
    CaptureStats? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_capture_stats(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_metadata(VideoMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.duration, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_64(self.frameRate, serializer);
    sse_encode_u_64(self.bitRate, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_u_64(self.fileSize, serializer);
  }
}

@sealed
class FFmpegManagerImpl extends RustOpaque implements FFmpegManager {
  // Not to be used by end users
  FFmpegManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FFmpegManagerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FFmpegManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FFmpegManager,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FFmpegManagerPtr,
  );

  /// 生成视频缩略图（第一帧）
  Future<String> generateThumbnail({
    required String videoUrl,
    required String outputPath,
  }) => RustLib.instance.api.crateApiFfmpegFFmpegManagerGenerateThumbnail(
    that: this,
    videoUrl: videoUrl,
    outputPath: outputPath,
  );

  /// 获取视频元数据
  Future<VideoMetadata> getMetadata({required String videoPath}) => RustLib
      .instance
      .api
      .crateApiFfmpegFFmpegManagerGetMetadata(that: this, videoPath: videoPath);

  /// 初始化 FFmpeg（如果需要则下载）
  Future<void> initialize() =>
      RustLib.instance.api.crateApiFfmpegFFmpegManagerInitialize(that: this);
}
