[package]
name = "capture_proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "capture_proxy"
path = "src/lib.rs"
# 改为动态库，用于动态加载
crate-type = ["cdylib", "rlib"]

[dependencies]
# 只启用必需的tokio features
tokio = { version = "1.49.0", features = [
  "rt-multi-thread",
  "net",
  "io-util",
  "sync",
  "time",
  "macros",
  "process",
  "fs",
], default-features = false }
# 只启用必需的hyper features
hyper = { version = "0.14.32", features = [
  "server",
  "client",
  "http1",
  "http2",
  "tcp",
  "stream",
], default-features = false }
serde = { version = "1.0.228", features = ["derive"], default-features = false }
serde_json = { version = "1.0.149", default-features = false, features = ["std"] }
regex = "1.12.2"
encoding_rs = "0.8.35"
tokio-rustls = { version = "0.23", default-features = false }
rustls = { version = "0.20", default-features = false, features = [
  "dangerous_configuration",
] }
rcgen = { version = "0.11.3", default-features = false, features = ["pem"] }
rustls-native-certs = "0.6"
base64 = "0.22.1"
rustls-pemfile = "2.2.0"
x509-parser = "0.18.0"
lazy_static = "1.5.0"  # C ABI 需要
libloading = "0.8"  # 测试用

[[example]]
name = "test_dll"
path = "test_dll.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
