[package]
name = "rust_lib_slime_works"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
lazy_static = "1.5.0"
# capture_proxy 使用动态加载，不再静态链接
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.8"                                      # 动态库加载
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
# ffmpeg_lib = { path = "ffmpeg_lib", optional = true }
tokio = { version = "1.49.0", features = [
  "rt-multi-thread",
  "sync",
], default-features = false }

dotenv = "0.15.0"

[features]
default = []
# ffmpeg = ["ffmpeg_lib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
members = [
  "capture_proxy",
  # "ffmpeg_lib",
]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [
  "processthreadsapi",
  "securitybaseapi",
  "winnt",
  "handleapi",
  "minwindef",
] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
