[package]
name = "aliyun_module"
version = "0.1.0"
edition = "2021"

[dependencies]
flutter_rust_bridge = "=2.11.1"
tokio = { version = "1.49.0", features = [
  "rt-multi-thread",
  "sync",
  "time",
  "macros",
], default-features = false }
reqwest = { version = "0.12", features = ["json", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
slime_logger = { path = "../slime_logger" }
chrono = { version = "0.4", features = ["serde"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
url = "2"
percent-encoding = "2.3"
base64 = "0.22"
lazy_static = "1.5"
uuid = { version = "1", features = ["v4"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[lib]
crate-type = ["staticlib", "rlib"]
