// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String aliyunDdnsInit({required String configJson}) => RustLib.instance.api
    .crateApiAliyunDdnsAliyunDdnsInit(configJson: configJson);

void aliyunDdnsUpdateConfig({required String configJson}) => RustLib
    .instance
    .api
    .crateApiAliyunDdnsAliyunDdnsUpdateConfig(configJson: configJson);

String aliyunDdnsGetConfig() =>
    RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsGetConfig();

void aliyunDdnsSetEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiAliyunDdnsAliyunDdnsSetEnabled(enabled: enabled);

Future<String> aliyunDdnsCheckAndUpdate() =>
    RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsCheckAndUpdate();

String aliyunDdnsGetStatus() =>
    RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsGetStatus();

String aliyunDdnsGetLogs() =>
    RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsGetLogs();

void aliyunDdnsClearLogs() =>
    RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsClearLogs();

Future<String> aliyunDdnsDescribeDomains({
  required String accessKeyId,
  required String accessKeySecret,
}) => RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsDescribeDomains(
  accessKeyId: accessKeyId,
  accessKeySecret: accessKeySecret,
);

Future<String> aliyunDdnsDescribeDomainRecords({
  required String accessKeyId,
  required String accessKeySecret,
  required String domainName,
}) => RustLib.instance.api.crateApiAliyunDdnsAliyunDdnsDescribeDomainRecords(
  accessKeyId: accessKeyId,
  accessKeySecret: accessKeySecret,
  domainName: domainName,
);
