// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_status`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// 获取本地语音识别部署状态
AsrStatusInfo asrGetStatus() => RustLib.instance.api.crateApiAsrAsrGetStatus();

/// 本地引擎是否已就绪（运行时 + 模型齐备）
bool asrIsReady() => RustLib.instance.api.crateApiAsrAsrIsReady();

/// 该文件是否可送去识别字幕
bool asrIsSupportedMedia({required String filePath}) =>
    RustLib.instance.api.crateApiAsrAsrIsSupportedMedia(filePath: filePath);

/// 一键部署：下载 sherpa-onnx 运行时 + SenseVoice/VAD 模型（阻塞，Dart 侧为 Future）
Future<void> asrDeploy() => RustLib.instance.api.crateApiAsrAsrDeploy();

/// 删除本地部署
void asrRemoveDeployment() =>
    RustLib.instance.api.crateApiAsrAsrRemoveDeployment();

/// 部署进度（0~100），空闲时 -1
double asrGetDeployProgress() =>
    RustLib.instance.api.crateApiAsrAsrGetDeployProgress();

/// 部署阶段：0 空闲 / 1 下载 / 2 解压 / 3 完成 / 4 失败
int asrGetDeployStage() => RustLib.instance.api.crateApiAsrAsrGetDeployStage();

/// 识别媒体文件并输出带时间轴的 SRT 字幕
///
/// * `output_path` - None 表示写到媒体文件同级目录（同名 .srt）
/// * `language`    - zh/en/ja/ko/yue/auto，None 为自动检测
Future<AsrSubtitleResultInfo> asrTranscribeToSrt({
  required String mediaPath,
  String? outputPath,
  String? language,
}) => RustLib.instance.api.crateApiAsrAsrTranscribeToSrt(
  mediaPath: mediaPath,
  outputPath: outputPath,
  language: language,
);

/// 取消正在进行的识别
bool asrCancelTranscribe() =>
    RustLib.instance.api.crateApiAsrAsrCancelTranscribe();

/// 识别进度（0~100），空闲时 -1
double asrGetTranscribeProgress() =>
    RustLib.instance.api.crateApiAsrAsrGetTranscribeProgress();

/// 把（可能是内网大模型返回的）字幕片段写成标准 SRT 文件
///
/// 文件写入统一放在 Rust 侧，Dart 只负责传数据与展示
String asrWriteSrt({
  required String mediaPath,
  required List<AsrSegmentInfo> segments,
  required String outputDir,
}) => RustLib.instance.api.crateApiAsrAsrWriteSrt(
  mediaPath: mediaPath,
  segments: segments,
  outputDir: outputDir,
);

/// 读取并解析已有的 .srt 字幕（翻译流程的入口）
List<AsrSegmentInfo> asrParseSrt({required String srtPath}) =>
    RustLib.instance.api.crateApiAsrAsrParseSrt(srtPath: srtPath);

/// 字幕片段（远程转写结果回传给 Rust 落盘用）
class AsrSegmentInfo {
  final BigInt startMs;
  final BigInt endMs;
  final String text;

  const AsrSegmentInfo({
    required this.startMs,
    required this.endMs,
    required this.text,
  });

  @override
  int get hashCode => startMs.hashCode ^ endMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AsrSegmentInfo &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text;
}

/// 本地 ASR 部署状态
class AsrStatusInfo {
  final bool runtimeReady;
  final String runtimeVersion;
  final String? runtimeExecPath;
  final bool modelReady;
  final bool vadReady;
  final String modelDir;
  final BigInt diskUsageBytes;

  const AsrStatusInfo({
    required this.runtimeReady,
    required this.runtimeVersion,
    this.runtimeExecPath,
    required this.modelReady,
    required this.vadReady,
    required this.modelDir,
    required this.diskUsageBytes,
  });

  @override
  int get hashCode =>
      runtimeReady.hashCode ^
      runtimeVersion.hashCode ^
      runtimeExecPath.hashCode ^
      modelReady.hashCode ^
      vadReady.hashCode ^
      modelDir.hashCode ^
      diskUsageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AsrStatusInfo &&
          runtimeType == other.runtimeType &&
          runtimeReady == other.runtimeReady &&
          runtimeVersion == other.runtimeVersion &&
          runtimeExecPath == other.runtimeExecPath &&
          modelReady == other.modelReady &&
          vadReady == other.vadReady &&
          modelDir == other.modelDir &&
          diskUsageBytes == other.diskUsageBytes;
}

/// 字幕生成结果
class AsrSubtitleResultInfo {
  final String srtPath;
  final BigInt segmentCount;
  final double? audioDurationSecs;
  final double wallTimeSecs;

  const AsrSubtitleResultInfo({
    required this.srtPath,
    required this.segmentCount,
    this.audioDurationSecs,
    required this.wallTimeSecs,
  });

  @override
  int get hashCode =>
      srtPath.hashCode ^
      segmentCount.hashCode ^
      audioDurationSecs.hashCode ^
      wallTimeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AsrSubtitleResultInfo &&
          runtimeType == other.runtimeType &&
          srtPath == other.srtPath &&
          segmentCount == other.segmentCount &&
          audioDurationSecs == other.audioDurationSecs &&
          wallTimeSecs == other.wallTimeSecs;
}
