// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_install_dir`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CaptureType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 启动代理服务器（通过动态模块）
String startCaptureProxy({required int port, String? installDir}) => RustLib
    .instance
    .api
    .crateApiCaptureStartCaptureProxy(port: port, installDir: installDir);

/// 停止代理服务器
String stopCaptureProxy({String? installDir}) => RustLib.instance.api
    .crateApiCaptureStopCaptureProxy(installDir: installDir);

/// 获取捕获状态
bool isProxyRunning({String? installDir}) =>
    RustLib.instance.api.crateApiCaptureIsProxyRunning(installDir: installDir);

/// 获取所有捕获的视频链接
List<String> getCapturedVideos({String? installDir}) => RustLib.instance.api
    .crateApiCaptureGetCapturedVideos(installDir: installDir);

/// 获取所有捕获的图片链接
List<String> getCapturedImages({String? installDir}) => RustLib.instance.api
    .crateApiCaptureGetCapturedImages(installDir: installDir);

/// 获取所有捕获的JSON数据
List<String> getCapturedJson({String? installDir}) =>
    RustLib.instance.api.crateApiCaptureGetCapturedJson(installDir: installDir);

/// 获取所有捕获的JavaScript文件
List<String> getCapturedJavascript({String? installDir}) => RustLib.instance.api
    .crateApiCaptureGetCapturedJavascript(installDir: installDir);

/// 清除所有捕获的数据
void clearCapturedData({String? installDir}) => RustLib.instance.api
    .crateApiCaptureClearCapturedData(installDir: installDir);

/// 获取捕获统计
CaptureStats? getCaptureStats({String? installDir}) =>
    RustLib.instance.api.crateApiCaptureGetCaptureStats(installDir: installDir);

/// 安装CA证书
String installCaCertificate({required String password, String? installDir}) =>
    RustLib.instance.api.crateApiCaptureInstallCaCertificate(
      password: password,
      installDir: installDir,
    );

/// 检查CA证书是否已安装
bool isCaCertificateInstalled({String? installDir}) => RustLib.instance.api
    .crateApiCaptureIsCaCertificateInstalled(installDir: installDir);

/// 检查是否以管理员身份运行（Windows）
bool isRunningAsAdministrator() =>
    RustLib.instance.api.crateApiCaptureIsRunningAsAdministrator();

/// 初始化日志系统
String initializeLogger({String? installDir}) => RustLib.instance.api
    .crateApiCaptureInitializeLogger(installDir: installDir);

/// 获取日志目录
String? getLoggerDirectory() =>
    RustLib.instance.api.crateApiCaptureGetLoggerDirectory();

/// 清理旧日志文件（保留最近 N 天）
int cleanupLoggerOldFiles({required int daysToKeep}) => RustLib.instance.api
    .crateApiCaptureCleanupLoggerOldFiles(daysToKeep: daysToKeep);

/// 写入信息日志
void writeLogInfo({required String message}) =>
    RustLib.instance.api.crateApiCaptureWriteLogInfo(message: message);

/// 写入错误日志
void writeLogError({required String message}) =>
    RustLib.instance.api.crateApiCaptureWriteLogError(message: message);

/// 捕获统计数据
class CaptureStats {
  final int total;
  final int videos;
  final int images;
  final int json;
  final int javascript;

  const CaptureStats({
    required this.total,
    required this.videos,
    required this.images,
    required this.json,
    required this.javascript,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      videos.hashCode ^
      images.hashCode ^
      json.hashCode ^
      javascript.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureStats &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          videos == other.videos &&
          images == other.images &&
          json == other.json &&
          javascript == other.javascript;
}
