// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CaptureType`, `IS_RUNNING`, `RUNTIME`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `deref`, `fmt`, `fmt`, `initialize`, `initialize`

/// 启动代理服务器
String startCaptureProxy({required int port}) =>
    RustLib.instance.api.crateApiCaptureStartCaptureProxy(port: port);

/// 停止代理服务器
String stopCaptureProxy() =>
    RustLib.instance.api.crateApiCaptureStopCaptureProxy();

/// 获取捕获状态
bool isProxyRunning() => RustLib.instance.api.crateApiCaptureIsProxyRunning();

/// 获取所有捕获的视频链接
List<String> getCapturedVideos() =>
    RustLib.instance.api.crateApiCaptureGetCapturedVideos();

/// 获取所有捕获的图片链接
List<String> getCapturedImages() =>
    RustLib.instance.api.crateApiCaptureGetCapturedImages();

/// 获取所有捕获的JSON数据
List<String> getCapturedJson() =>
    RustLib.instance.api.crateApiCaptureGetCapturedJson();

/// 获取所有捕获的JavaScript链接
List<String> getCapturedJavascript() =>
    RustLib.instance.api.crateApiCaptureGetCapturedJavascript();

/// 清除所有捕获的数据
void clearCapturedData() =>
    RustLib.instance.api.crateApiCaptureClearCapturedData();

/// 获取捕获数据的数量统计
CaptureStats getCaptureStats() =>
    RustLib.instance.api.crateApiCaptureGetCaptureStats();

/// 获取CA证书路径
String getCaCertificatePath() =>
    RustLib.instance.api.crateApiCaptureGetCaCertificatePath();

/// 使用管理员密码安装CA证书（macOS需要密码）
String installCaCertificate({required String password}) => RustLib.instance.api
    .crateApiCaptureInstallCaCertificate(password: password);

/// 检查CA证书是否已安装到系统
bool isCaCertificateInstalled() =>
    RustLib.instance.api.crateApiCaptureIsCaCertificateInstalled();

/// 检查当前进程是否以管理员权限运行（仅Windows）
bool isRunningAsAdministrator() =>
    RustLib.instance.api.crateApiCaptureIsRunningAsAdministrator();

/// 捕获统计数据
class CaptureStats {
  final int total;
  final int videos;
  final int images;
  final int json;
  final int javascript;

  const CaptureStats({
    required this.total,
    required this.videos,
    required this.images,
    required this.json,
    required this.javascript,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      videos.hashCode ^
      images.hashCode ^
      json.hashCode ^
      javascript.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureStats &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          videos == other.videos &&
          images == other.images &&
          json == other.json &&
          javascript == other.javascript;
}
