// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void extractInitPasswordTable({required String dbPath}) => RustLib.instance.api
    .crateApiExtractExtractInitPasswordTable(dbPath: dbPath);

String extractListPasswordsJson() =>
    RustLib.instance.api.crateApiExtractExtractListPasswordsJson();

String extractAddPassword({required String password, String? remark}) => RustLib
    .instance
    .api
    .crateApiExtractExtractAddPassword(password: password, remark: remark);

bool extractRemovePassword({required String id}) =>
    RustLib.instance.api.crateApiExtractExtractRemovePassword(id: id);

bool extractUpdatePasswordRemark({required String id, String? remark}) =>
    RustLib.instance.api.crateApiExtractExtractUpdatePasswordRemark(
      id: id,
      remark: remark,
    );

String extractScanArchivesJson({required String dir}) =>
    RustLib.instance.api.crateApiExtractExtractScanArchivesJson(dir: dir);

String extractGetProgressJson() =>
    RustLib.instance.api.crateApiExtractExtractGetProgressJson();

String extractGetResultJson() =>
    RustLib.instance.api.crateApiExtractExtractGetResultJson();

void extractStart({required String configJson}) =>
    RustLib.instance.api.crateApiExtractExtractStart(configJson: configJson);

void extractCancel() => RustLib.instance.api.crateApiExtractExtractCancel();

String extractFormatFileSize({required BigInt bytes}) =>
    RustLib.instance.api.crateApiExtractExtractFormatFileSize(bytes: bytes);
