// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_ffmpeg_path`, `get_ffprobe_path`, `parse_frame_rate`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FFMPEG_MANAGER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `fmt`, `fmt`, `initialize`

/// 初始化 FFmpeg
///
/// # Arguments
/// * `windows_url` - Windows FFmpeg 下载 URL（从 .env 读取）
/// * `macos_url` - macOS FFmpeg 下载 URL（从 .env 读取）
/// * `install_dir` - 安装目录路径
Future<String> initializeFfmpeg({
  required String windowsUrl,
  required String macosUrl,
  required String installDir,
}) => RustLib.instance.api.crateApiFfmpegInitializeFfmpeg(
  windowsUrl: windowsUrl,
  macosUrl: macosUrl,
  installDir: installDir,
);

/// 获取视频元数据
///
/// # Arguments
/// * `video_path` - 视频文件路径或 URL
Future<VideoMetadata> getVideoMetadata({required String videoPath}) =>
    RustLib.instance.api.crateApiFfmpegGetVideoMetadata(videoPath: videoPath);

/// 生成视频缩略图
///
/// # Arguments
/// * `video_url` - 视频 URL
/// * `cache_dir` - 系统缓存目录路径
///
/// # Returns
/// 生成的缩略图文件路径
Future<String> generateVideoThumbnail({
  required String videoUrl,
  required String cacheDir,
}) => RustLib.instance.api.crateApiFfmpegGenerateVideoThumbnail(
  videoUrl: videoUrl,
  cacheDir: cacheDir,
);

/// 检查 FFmpeg 是否已安装
Future<bool> isFfmpegInstalled({required String installDir}) => RustLib
    .instance
    .api
    .crateApiFfmpegIsFfmpegInstalled(installDir: installDir);

/// 获取 FFmpeg 版本信息
Future<String> getFfmpegVersion({required String installDir}) =>
    RustLib.instance.api.crateApiFfmpegGetFfmpegVersion(installDir: installDir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FFmpegManager>>
abstract class FFmpegManager implements RustOpaqueInterface {
  /// 生成视频缩略图（第一帧）
  Future<String> generateThumbnail({
    required String videoUrl,
    required String outputPath,
  });

  /// 获取视频元数据
  Future<VideoMetadata> getMetadata({required String videoPath});

  /// 初始化 FFmpeg（如果需要则下载）
  Future<void> initialize();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建 FFmpeg 管理器
  static Future<FFmpegManager> newInstance({required FFmpegConfig config}) =>
      RustLib.instance.api.crateApiFfmpegFFmpegManagerNew(config: config);
}

/// FFmpeg 配置
class FFmpegConfig {
  final String windowsUrl;
  final String macosUrl;
  final String installDir;

  const FFmpegConfig({
    required this.windowsUrl,
    required this.macosUrl,
    required this.installDir,
  });

  @override
  int get hashCode =>
      windowsUrl.hashCode ^ macosUrl.hashCode ^ installDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FFmpegConfig &&
          runtimeType == other.runtimeType &&
          windowsUrl == other.windowsUrl &&
          macosUrl == other.macosUrl &&
          installDir == other.installDir;
}

/// 视频元数据
class VideoMetadata {
  final double duration;
  final int width;
  final int height;
  final double frameRate;
  final BigInt bitRate;
  final String codec;
  final BigInt fileSize;

  const VideoMetadata({
    required this.duration,
    required this.width,
    required this.height,
    required this.frameRate,
    required this.bitRate,
    required this.codec,
    required this.fileSize,
  });

  @override
  int get hashCode =>
      duration.hashCode ^
      width.hashCode ^
      height.hashCode ^
      frameRate.hashCode ^
      bitRate.hashCode ^
      codec.hashCode ^
      fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoMetadata &&
          runtimeType == other.runtimeType &&
          duration == other.duration &&
          width == other.width &&
          height == other.height &&
          frameRate == other.frameRate &&
          bitRate == other.bitRate &&
          codec == other.codec &&
          fileSize == other.fileSize;
}
