// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `category_to_json`, `game_to_json`, `json_to_category`, `json_to_game`, `json_to_progress`, `json_to_session`, `ms_to_sec_opt`, `ms_to_sec`, `progress_to_json`, `session_to_json`, `sv`, `svs`

void gameLibraryInit({required String dbPath}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryInit(dbPath: dbPath);

bool gameLibraryIsReady() =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryIsReady();

void gameLibraryClose() =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryClose();

Future<String> gameLibraryGetGamesJson() =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryGetGamesJson();

Future<String> gameLibraryGetGameByIdJson({required String gameId}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryGetGameByIdJson(gameId: gameId);

Future<String> gameLibraryAddGameJson({required String gameJson}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryAddGameJson(gameJson: gameJson);

Future<void> gameLibraryUpdateGameJson({required String gameJson}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryUpdateGameJson(gameJson: gameJson);

Future<void> gameLibraryDeleteGame({required String gameId}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryDeleteGame(gameId: gameId);

Future<String> gameLibraryGetCategoriesJson() =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryGetCategoriesJson();

Future<String> gameLibraryUpsertCategoryJson({required String categoryJson}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryUpsertCategoryJson(
      categoryJson: categoryJson,
    );

Future<void> gameLibraryDeleteCategory({required String categoryId}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryDeleteCategory(categoryId: categoryId);

Future<void> gameLibraryAddGameToCategory({
  required String gameId,
  required String categoryId,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryAddGameToCategory(
  gameId: gameId,
  categoryId: categoryId,
);

Future<void> gameLibraryRemoveGameFromCategory({
  required String gameId,
  required String categoryId,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryRemoveGameFromCategory(
  gameId: gameId,
  categoryId: categoryId,
);

Future<List<String>> gameLibraryGetGameCategoryIds({required String gameId}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryGetGameCategoryIds(
      gameId: gameId,
    );

Future<void> gameLibraryToggleFavorite({
  required String gameId,
  required bool favorite,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryToggleFavorite(
  gameId: gameId,
  favorite: favorite,
);

Future<bool> gameLibraryIsFavorite({required String gameId}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryIsFavorite(gameId: gameId);

Future<void> gameLibraryAddPlaySessionJson({required String sessionJson}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryAddPlaySessionJson(
      sessionJson: sessionJson,
    );

Future<String> gameLibraryGetPlaySessionsJson({required String gameId}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryGetPlaySessionsJson(
      gameId: gameId,
    );

Future<String> gameLibraryUpsertProgressJson({required String progressJson}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryUpsertProgressJson(
      progressJson: progressJson,
    );

Future<String> gameLibraryGetProgressJson({required String gameId}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryGetProgressJson(gameId: gameId);

Future<String> gameLibraryGetStatsJson({
  required PlatformInt64 startTsSec,
  required PlatformInt64 endTsSec,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryGetStatsJson(
  startTsSec: startTsSec,
  endTsSec: endTsSec,
);

Future<String> gameLibraryGetHomePageDataJson() =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryGetHomePageDataJson();

Future<PlatformInt64> gameLibraryLaunchGame({
  required String exePath,
  required String workingDir,
  required bool useOpen,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryLaunchGame(
  exePath: exePath,
  workingDir: workingDir,
  useOpen: useOpen,
);

String gameLibraryDeriveGameName({required String path}) => RustLib.instance.api
    .crateApiGameLibraryGameLibraryDeriveGameName(path: path);

Future<String> gameLibraryScanDirectoryJson({required List<String> paths}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryScanDirectoryJson(
      paths: paths,
    );

Future<List<String>> gameLibraryCheckPathsExist({
  required List<String> paths,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryCheckPathsExist(
  paths: paths,
);

Future<String> gameLibraryGetSettingsJson() =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryGetSettingsJson();

Future<void> gameLibrarySaveSettingsJson({required String settingsJson}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibrarySaveSettingsJson(
      settingsJson: settingsJson,
    );

Future<String> gameLibraryFetchMoegirl({required String gameName}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryFetchMoegirl(gameName: gameName);

Future<String> gameLibrarySearch2DfanSubject({required String gameName}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibrarySearch2DfanSubject(
      gameName: gameName,
    );

Future<String> gameLibraryFetch2DfanDownloadPath({
  required String subjectPath,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryFetch2DfanDownloadPath(
  subjectPath: subjectPath,
);

Future<String> gameLibraryFetch2DfanDownloadInfo({
  required String downloadPath,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryFetch2DfanDownloadInfo(
  downloadPath: downloadPath,
);

Future<void> gameLibraryDownloadFile({
  required String url,
  required String savePath,
}) => RustLib.instance.api.crateApiGameLibraryGameLibraryDownloadFile(
  url: url,
  savePath: savePath,
);

/// 用游戏名在 Steam/VNDB/Bangumi 中搜索元数据。
/// 找到则返回 JSON 字符串，未找到则返回空字符串。
Future<String> gameLibrarySearchMetadataByName({required String name}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibrarySearchMetadataByName(
      name: name,
    );

/// 检测指定 PID 的进程是否仍在运行
Future<bool> gameLibraryIsPidAlive({required PlatformInt64 pid}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryIsPidAlive(pid: pid);

/// 查找运行中且路径位于指定目录下的进程 PID 列表（仅 Windows）
Future<Int64List> gameLibraryFindProcessesInDir({required String gameDir}) =>
    RustLib.instance.api.crateApiGameLibraryGameLibraryFindProcessesInDir(
      gameDir: gameDir,
    );

/// 启发式检测游戏存档目录，返回路径或空字符串
String gameLibraryDetectSaveFolder({required String gameDir}) => RustLib
    .instance
    .api
    .crateApiGameLibraryGameLibraryDetectSaveFolder(gameDir: gameDir);
