// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取已注册的HTTP Bridge处理器列表
List<(String, String)> getRegisteredHandlers() =>
    RustLib.instance.api.crateApiHttpBridgeGetRegisteredHandlers();

/// 调用HTTP Bridge处理器
String callHandler({
  required String module,
  required String function,
  required String params,
}) => RustLib.instance.api.crateApiHttpBridgeCallHandler(
  module: module,
  function: function,
  params: params,
);

/// 初始化HTTP Bridge（注册所有接口）
bool initHttpBridge() =>
    RustLib.instance.api.crateApiHttpBridgeInitHttpBridge();

/// 启动本地节点服务器（仅桌面端）
///
/// - host: 监听地址，通常为 "0.0.0.0"
/// - port: 监听端口，默认 17888
/// - name: 节点名称
/// - auth_code: 授权码明文，空串表示不启用校验；非空时除 /health 外的请求都必须
///   带 `X-SW-Auth: <sha256(授权码)>`，服务端只保留摘要
void startNodeServer({
  required String host,
  required int port,
  required String name,
  required String authCode,
}) => RustLib.instance.api.crateApiHttpBridgeStartNodeServer(
  host: host,
  port: port,
  name: name,
  authCode: authCode,
);

/// 停止本地节点服务器
void stopNodeServer() =>
    RustLib.instance.api.crateApiHttpBridgeStopNodeServer();

/// 检查节点服务器是否在运行
bool isNodeServerRunning() =>
    RustLib.instance.api.crateApiHttpBridgeIsNodeServerRunning();
