// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取已注册的HTTP Bridge处理器列表
List<(String, String)> getRegisteredHandlers() =>
    RustLib.instance.api.crateApiHttpBridgeGetRegisteredHandlers();

/// 调用HTTP Bridge处理器
String callHandler({
  required String module,
  required String function,
  required String params,
}) => RustLib.instance.api.crateApiHttpBridgeCallHandler(
  module: module,
  function: function,
  params: params,
);

/// 初始化HTTP Bridge（注册所有接口）
bool initHttpBridge() =>
    RustLib.instance.api.crateApiHttpBridgeInitHttpBridge();
