// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化局域网传输服务
void lanTransferInit() =>
    RustLib.instance.api.crateApiLanTransferLanTransferInit();

/// 创建并启动传输管理器
Future<void> lanTransferStart({required int port}) =>
    RustLib.instance.api.crateApiLanTransferLanTransferStart(port: port);

/// 停止传输管理器
Future<void> lanTransferStop() =>
    RustLib.instance.api.crateApiLanTransferLanTransferStop();

/// 获取本机设备信息
Future<String> lanTransferGetLocalDevice({required int port}) => RustLib
    .instance
    .api
    .crateApiLanTransferLanTransferGetLocalDevice(port: port);

/// 获取已发现的设备列表
Future<List<String>> lanTransferGetDevices() =>
    RustLib.instance.api.crateApiLanTransferLanTransferGetDevices();

/// 发送文本消息
Future<String> lanTransferSendText({
  required String targetIp,
  required int targetPort,
  required String targetDeviceId,
  required String text,
}) => RustLib.instance.api.crateApiLanTransferLanTransferSendText(
  targetIp: targetIp,
  targetPort: targetPort,
  targetDeviceId: targetDeviceId,
  text: text,
);

/// 发送文件
Future<String> lanTransferSendFile({
  required String targetIp,
  required int targetPort,
  required String targetDeviceId,
  required String filePath,
}) => RustLib.instance.api.crateApiLanTransferLanTransferSendFile(
  targetIp: targetIp,
  targetPort: targetPort,
  targetDeviceId: targetDeviceId,
  filePath: filePath,
);

/// 接受传输
Future<void> lanTransferAccept({required String transferId}) => RustLib
    .instance
    .api
    .crateApiLanTransferLanTransferAccept(transferId: transferId);

/// 拒绝传输
Future<void> lanTransferReject({required String transferId}) => RustLib
    .instance
    .api
    .crateApiLanTransferLanTransferReject(transferId: transferId);

/// 取消传输
Future<void> lanTransferCancel({required String transferId}) => RustLib
    .instance
    .api
    .crateApiLanTransferLanTransferCancel(transferId: transferId);

/// 获取所有传输记录
Future<List<String>> lanTransferGetTransfers() =>
    RustLib.instance.api.crateApiLanTransferLanTransferGetTransfers();

/// 添加信任设备
Future<void> lanTransferAddTrusted({
  required String deviceId,
  required String deviceName,
}) => RustLib.instance.api.crateApiLanTransferLanTransferAddTrusted(
  deviceId: deviceId,
  deviceName: deviceName,
);

/// 移除信任设备
Future<void> lanTransferRemoveTrusted({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiLanTransferLanTransferRemoveTrusted(deviceId: deviceId);

/// 检查是否为信任设备
Future<bool> lanTransferIsTrusted({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiLanTransferLanTransferIsTrusted(deviceId: deviceId);

/// 获取信任设备列表
Future<List<String>> lanTransferGetTrustedDevices() =>
    RustLib.instance.api.crateApiLanTransferLanTransferGetTrustedDevices();
