// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 流水账模块 API：把 ledger_module 的 FFI 面原样转发出来。
///
/// 约定与 power_stats 一致：入参出参都是 snake_case 的 JSON 字符串，
/// 字段增删只在这里报错，不会把 ledger 的类型扩散到主 crate。
/// 只有纯本地读写用 `#[frb(sync)]`，凡是可能联网的（收信、连接自检）都走 async，
/// 否则同步调用会卡住 UI isolate。
String ledgerInit({required String dbPathJson}) =>
    RustLib.instance.api.crateApiLedgerLedgerInit(dbPathJson: dbPathJson);

bool ledgerIsReady() => RustLib.instance.api.crateApiLedgerLedgerIsReady();

String ledgerVersion() => RustLib.instance.api.crateApiLedgerLedgerVersion();

String ledgerListAccounts() =>
    RustLib.instance.api.crateApiLedgerLedgerListAccounts();

PlatformInt64 ledgerUpsertAccount({required String accountJson}) => RustLib
    .instance
    .api
    .crateApiLedgerLedgerUpsertAccount(accountJson: accountJson);

String ledgerDeleteAccount({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiLedgerLedgerDeleteAccount(id: id);

String ledgerListCategories({required String direction}) => RustLib.instance.api
    .crateApiLedgerLedgerListCategories(direction: direction);

PlatformInt64 ledgerUpsertCategory({required String categoryJson}) => RustLib
    .instance
    .api
    .crateApiLedgerLedgerUpsertCategory(categoryJson: categoryJson);

String ledgerDeleteCategory({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiLedgerLedgerDeleteCategory(id: id);

String ledgerListMerchantMemory() =>
    RustLib.instance.api.crateApiLedgerLedgerListMerchantMemory();

void ledgerForgetMerchant({required String merchantKey}) => RustLib.instance.api
    .crateApiLedgerLedgerForgetMerchant(merchantKey: merchantKey);

String ledgerListTransactions({required String filterJson}) => RustLib
    .instance
    .api
    .crateApiLedgerLedgerListTransactions(filterJson: filterJson);

PlatformInt64 ledgerCountTransactions({required String filterJson}) => RustLib
    .instance
    .api
    .crateApiLedgerLedgerCountTransactions(filterJson: filterJson);

PlatformInt64 ledgerAddTransaction({required String txJson}) =>
    RustLib.instance.api.crateApiLedgerLedgerAddTransaction(txJson: txJson);

void ledgerUpdateTransaction({required String txJson}) =>
    RustLib.instance.api.crateApiLedgerLedgerUpdateTransaction(txJson: txJson);

bool ledgerDeleteTransaction({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiLedgerLedgerDeleteTransaction(id: id);

String ledgerCheckDuplicate({required String dupJson}) =>
    RustLib.instance.api.crateApiLedgerLedgerCheckDuplicate(dupJson: dupJson);

String ledgerStatsByDay({required String filterJson}) =>
    RustLib.instance.api.crateApiLedgerLedgerStatsByDay(filterJson: filterJson);

String ledgerStatsByCategory({required String filterJson}) => RustLib
    .instance
    .api
    .crateApiLedgerLedgerStatsByCategory(filterJson: filterJson);

String ledgerStatsByMerchant({
  required String filterJson,
  required PlatformInt64 top,
}) => RustLib.instance.api.crateApiLedgerLedgerStatsByMerchant(
  filterJson: filterJson,
  top: top,
);

String ledgerStatsSummary({required String filterJson}) => RustLib.instance.api
    .crateApiLedgerLedgerStatsSummary(filterJson: filterJson);

String ledgerStatsByMonth({required PlatformInt64 months}) =>
    RustLib.instance.api.crateApiLedgerLedgerStatsByMonth(months: months);

String ledgerListRules() =>
    RustLib.instance.api.crateApiLedgerLedgerListRules();

PlatformInt64 ledgerUpsertRule({
  required String ruleJson,
  required String password,
}) => RustLib.instance.api.crateApiLedgerLedgerUpsertRule(
  ruleJson: ruleJson,
  password: password,
);

void ledgerDeleteRule({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiLedgerLedgerDeleteRule(id: id);

void ledgerSetRuleEnabled({required PlatformInt64 id, required bool enabled}) =>
    RustLib.instance.api.crateApiLedgerLedgerSetRuleEnabled(
      id: id,
      enabled: enabled,
    );

void ledgerSetRulePassword({
  required PlatformInt64 ruleId,
  required String password,
}) => RustLib.instance.api.crateApiLedgerLedgerSetRulePassword(
  ruleId: ruleId,
  password: password,
);

bool ledgerHasRulePassword({required PlatformInt64 ruleId}) =>
    RustLib.instance.api.crateApiLedgerLedgerHasRulePassword(ruleId: ruleId);

String ledgerRuleDetail({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiLedgerLedgerRuleDetail(id: id);

String ledgerTemplates() =>
    RustLib.instance.api.crateApiLedgerLedgerTemplates();

String ledgerParsePreview({
  required String html,
  required String templateId,
  required String templateConfig,
}) => RustLib.instance.api.crateApiLedgerLedgerParsePreview(
  html: html,
  templateId: templateId,
  templateConfig: templateConfig,
);

Future<String> ledgerCheckRule({
  required PlatformInt64 ruleId,
  required String password,
}) => RustLib.instance.api.crateApiLedgerLedgerCheckRule(
  ruleId: ruleId,
  password: password,
);

Future<String> ledgerFetchEmails({
  required String configJson,
  required String password,
  required BigInt limit,
}) => RustLib.instance.api.crateApiLedgerLedgerFetchEmails(
  configJson: configJson,
  password: password,
  limit: limit,
);

Future<String> ledgerTestConnection({
  required String configJson,
  required String password,
  required bool wantFolders,
}) => RustLib.instance.api.crateApiLedgerLedgerTestConnection(
  configJson: configJson,
  password: password,
  wantFolders: wantFolders,
);

Future<String> ledgerListFolders({
  required String configJson,
  required String password,
}) => RustLib.instance.api.crateApiLedgerLedgerListFolders(
  configJson: configJson,
  password: password,
);

String ledgerListPending({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiLedgerLedgerListPending(limit: limit);

String ledgerListReceivedEmails({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiLedgerLedgerListReceivedEmails(limit: limit);

String ledgerEmailTransactions({required PlatformInt64 emailId}) => RustLib
    .instance
    .api
    .crateApiLedgerLedgerEmailTransactions(emailId: emailId);

PlatformInt64 ledgerPendingCount() =>
    RustLib.instance.api.crateApiLedgerLedgerPendingCount();

void ledgerConfirmTx({
  required PlatformInt64 txId,
  required String patchJson,
}) => RustLib.instance.api.crateApiLedgerLedgerConfirmTx(
  txId: txId,
  patchJson: patchJson,
);

PlatformInt64 ledgerConfirmAll({
  required PlatformInt64 emailId,
  required String patchJson,
}) => RustLib.instance.api.crateApiLedgerLedgerConfirmAll(
  emailId: emailId,
  patchJson: patchJson,
);

PlatformInt64 ledgerIgnoreEmail({required PlatformInt64 emailId}) =>
    RustLib.instance.api.crateApiLedgerLedgerIgnoreEmail(emailId: emailId);

void ledgerIgnoreTx({required PlatformInt64 txId}) =>
    RustLib.instance.api.crateApiLedgerLedgerIgnoreTx(txId: txId);

PlatformInt64 ledgerPurgeEmail({required PlatformInt64 emailId}) =>
    RustLib.instance.api.crateApiLedgerLedgerPurgeEmail(emailId: emailId);

void ledgerSchedulerStart() =>
    RustLib.instance.api.crateApiLedgerLedgerSchedulerStart();

void ledgerSchedulerStop() =>
    RustLib.instance.api.crateApiLedgerLedgerSchedulerStop();

String ledgerSchedulerStatus() =>
    RustLib.instance.api.crateApiLedgerLedgerSchedulerStatus();

String ledgerGetLogs({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiLedgerLedgerGetLogs(limit: limit);

void ledgerClearLogs() => RustLib.instance.api.crateApiLedgerLedgerClearLogs();
