// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> initLogger({required String installDir}) =>
    RustLib.instance.api.crateApiLoggerInitLogger(installDir: installDir);

Future<void> logInfo({required String message}) =>
    RustLib.instance.api.crateApiLoggerLogInfo(message: message);

Future<void> logWarn({required String message}) =>
    RustLib.instance.api.crateApiLoggerLogWarn(message: message);

Future<void> logError({required String message}) =>
    RustLib.instance.api.crateApiLoggerLogError(message: message);

Future<void> logDebug({required String message}) =>
    RustLib.instance.api.crateApiLoggerLogDebug(message: message);

Future<String?> getLogDir() => RustLib.instance.api.crateApiLoggerGetLogDir();

Future<BigInt> cleanupOldLogs({required int daysToKeep}) =>
    RustLib.instance.api.crateApiLoggerCleanupOldLogs(daysToKeep: daysToKeep);
