// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_history_table`, `migrate_scattered_manga_history`

/// 初始化 Manga 客户端
void mangaInit() => RustLib.instance.api.crateApiMangaMangaInit();

/// 设置代理
void mangaSetProxy({required String proxyUrl}) =>
    RustLib.instance.api.crateApiMangaMangaSetProxy(proxyUrl: proxyUrl);

/// 直接写入 Token
void mangaSetToken({required String token}) =>
    RustLib.instance.api.crateApiMangaMangaSetToken(token: token);

/// 获取当前 Token
String mangaGetToken() => RustLib.instance.api.crateApiMangaMangaGetToken();

/// 登出并清除 Token
void mangaLogout() => RustLib.instance.api.crateApiMangaMangaLogout();

/// 设置 API 分流模式
/// - 0: 标准直连
/// - 2: 分流2 (IP: 104.21.91.145)
/// - 3: 分流3 (IP: 188.114.98.153)
/// - 4: CDN分流 (自定义IP，默认 104.18.227.172)
/// - 5: JP反代 (https://bika-api.jpacg.cc)
/// - 6: US反代 (https://bika2-api.jpacg.cc)
void mangaSetChannel({required int mode, required String custom}) => RustLib
    .instance
    .api
    .crateApiMangaMangaSetChannel(mode: mode, custom: custom);

/// 设置图片服务器（如 s3.picacomic.com / storage1.picacomic.com）
void mangaSetImageServer({required String server}) =>
    RustLib.instance.api.crateApiMangaMangaSetImageServer(server: server);

/// 获取当前图片服务器
String mangaGetImageServer() =>
    RustLib.instance.api.crateApiMangaMangaGetImageServer();

/// 测试分流节点连通性，返回延迟(ms)
Future<BigInt> mangaTestChannel({required int mode, required String custom}) =>
    RustLib.instance.api.crateApiMangaMangaTestChannel(
      mode: mode,
      custom: custom,
    );

/// 登录
Future<String> mangaLogin({required String email, required String password}) =>
    RustLib.instance.api.crateApiMangaMangaLogin(
      email: email,
      password: password,
    );

/// 获取用户信息
Future<String> mangaGetUserProfile() =>
    RustLib.instance.api.crateApiMangaMangaGetUserProfile();

/// 每日签到
Future<String> mangaPunchIn() =>
    RustLib.instance.api.crateApiMangaMangaPunchIn();

/// 获取首页精选推荐
Future<String> mangaGetCollections() =>
    RustLib.instance.api.crateApiMangaMangaGetCollections();

/// 获取随机漫画
Future<String> mangaGetRandomComics() =>
    RustLib.instance.api.crateApiMangaMangaGetRandomComics();

/// 获取所有分类
Future<String> mangaGetCategories() =>
    RustLib.instance.api.crateApiMangaMangaGetCategories();

/// 按分类获取漫画列表
Future<String> mangaGetComicsByCategory({
  required String category,
  required int page,
  required String sort,
}) => RustLib.instance.api.crateApiMangaMangaGetComicsByCategory(
  category: category,
  page: page,
  sort: sort,
);

/// 高级搜索
Future<String> mangaSearchComics({
  required String keyword,
  required List<String> categories,
  required int page,
  required String sort,
}) => RustLib.instance.api.crateApiMangaMangaSearchComics(
  keyword: keyword,
  categories: categories,
  page: page,
  sort: sort,
);

/// 热门搜索关键词
Future<String> mangaGetKeywords() =>
    RustLib.instance.api.crateApiMangaMangaGetKeywords();

/// 排行榜
Future<String> mangaGetRankings({required String timeType}) =>
    RustLib.instance.api.crateApiMangaMangaGetRankings(timeType: timeType);

/// 漫画详情
Future<String> mangaGetComicDetail({required String comicId}) =>
    RustLib.instance.api.crateApiMangaMangaGetComicDetail(comicId: comicId);

/// 漫画相关推荐
Future<String> mangaGetComicRecommendations({required String comicId}) =>
    RustLib.instance.api.crateApiMangaMangaGetComicRecommendations(
      comicId: comicId,
    );

/// 章节列表
Future<String> mangaGetComicEps({required String comicId, required int page}) =>
    RustLib.instance.api.crateApiMangaMangaGetComicEps(
      comicId: comicId,
      page: page,
    );

/// 章节图片
Future<String> mangaGetEpsPages({
  required String comicId,
  required int epsOrder,
  required int page,
}) => RustLib.instance.api.crateApiMangaMangaGetEpsPages(
  comicId: comicId,
  epsOrder: epsOrder,
  page: page,
);

/// 收藏列表
Future<String> mangaGetFavourites({required int page, required String sort}) =>
    RustLib.instance.api.crateApiMangaMangaGetFavourites(
      page: page,
      sort: sort,
    );

/// 切换收藏状态
Future<String> mangaToggleFavourite({required String comicId}) =>
    RustLib.instance.api.crateApiMangaMangaToggleFavourite(comicId: comicId);

/// 切换点赞状态
Future<String> mangaToggleLike({required String comicId}) =>
    RustLib.instance.api.crateApiMangaMangaToggleLike(comicId: comicId);

/// 评论列表
Future<String> mangaGetComments({required String comicId, required int page}) =>
    RustLib.instance.api.crateApiMangaMangaGetComments(
      comicId: comicId,
      page: page,
    );

/// 子评论列表
Future<String> mangaGetCommentChildren({
  required String commentId,
  required int page,
}) => RustLib.instance.api.crateApiMangaMangaGetCommentChildren(
  commentId: commentId,
  page: page,
);

/// 发表评论
Future<String> mangaSendComment({
  required String comicId,
  required String content,
}) => RustLib.instance.api.crateApiMangaMangaSendComment(
  comicId: comicId,
  content: content,
);

/// 点赞评论
Future<String> mangaLikeComment({required String commentId}) =>
    RustLib.instance.api.crateApiMangaMangaLikeComment(commentId: commentId);

/// 构建完整图片 URL
String mangaBuildImageUrl({required String fileServer, required String path}) =>
    RustLib.instance.api.crateApiMangaMangaBuildImageUrl(
      fileServer: fileServer,
      path: path,
    );

Future<Uint8List> mangaFetchImage({
  required String fileServer,
  required String path,
}) => RustLib.instance.api.crateApiMangaMangaFetchImage(
  fileServer: fileServer,
  path: path,
);

/// 初始化漫画历史记录数据库
///
/// 在应用启动时调用一次，传入应用数据目录下的 db 文件路径（由 Dart path_provider 提供）。
/// 表绑定到该专属文件，不受其他模块初始化顺序影响。
void mangaInitHistory({required String dbPath}) =>
    RustLib.instance.api.crateApiMangaMangaInitHistory(dbPath: dbPath);

/// 读取所有历史记录，返回 JSON 字符串（未初始化或无数据时返回空字符串）
String mangaLoadHistory() =>
    RustLib.instance.api.crateApiMangaMangaLoadHistory();

/// 持久化历史记录（完整 JSON 字符串，由 Dart 构造后传入）
void mangaSaveHistoryRaw({required String json}) =>
    RustLib.instance.api.crateApiMangaMangaSaveHistoryRaw(json: json);

/// 清空全部历史记录
void mangaClearHistory() =>
    RustLib.instance.api.crateApiMangaMangaClearHistory();
