// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_collection`, `convert_folder`, `convert_item`, `convert_kind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

List<MediaCollection> getAllMediaCollections() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllMediaCollections();

List<MediaFolder> getAllMediaFolders() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllMediaFolders();

List<MediaFolder> getChildMediaFolders({required String parentId}) =>
    RustLib.instance.api.crateApiMediaCollectionGetChildMediaFolders(parentId: parentId);

List<MediaItem> getMediaCollectionItems({required String collectionId}) =>
    RustLib.instance.api.crateApiMediaCollectionGetMediaCollectionItems(collectionId: collectionId);

Future<MediaCollection> importMediaFolder({required String folderPath}) =>
    RustLib.instance.api.crateApiMediaCollectionImportMediaFolder(folderPath: folderPath);

Future<List<MediaCollection>> scanMediaFolders({required String folderPath}) =>
    RustLib.instance.api.crateApiMediaCollectionScanMediaFolders(folderPath: folderPath);

MediaFolder createMediaFolder({required String name}) =>
    RustLib.instance.api.crateApiMediaCollectionCreateMediaFolder(name: name);

MediaFolder createChildMediaFolder({required String name, required String parentId}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionCreateChildMediaFolder(name: name, parentId: parentId);

bool renameMediaCollection({required String collectionId, required String title}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionRenameMediaCollection(collectionId: collectionId, title: title);

bool moveMediaCollectionToFolder({required String collectionId, String? folderId}) =>
    RustLib.instance.api.crateApiMediaCollectionMoveMediaCollectionToFolder(
      collectionId: collectionId,
      folderId: folderId,
    );

bool renameMediaFolder({required String folderId, required String name}) =>
    RustLib.instance.api.crateApiMediaCollectionRenameMediaFolder(folderId: folderId, name: name);

bool deleteMediaFolder({required String folderId}) =>
    RustLib.instance.api.crateApiMediaCollectionDeleteMediaFolder(folderId: folderId);

bool deleteMediaCollection({required String collectionId}) =>
    RustLib.instance.api.crateApiMediaCollectionDeleteMediaCollection(collectionId: collectionId);

/// Generate (or serve from disk cache) a JPEG thumbnail for [filePath] at
/// [width] pixels wide.  Tries ffmpeg first (handles HEIC/AVIF), then falls
/// back to pure-Rust `image` crate.  Returns the cached thumbnail file path,
/// or `null` on failure.
String? ensureCoverThumbnail({required String filePath, required int width}) => RustLib.instance.api
    .crateApiMediaCollectionEnsureCoverThumbnail(filePath: filePath, width: width);

/// Return size + file-path list for every local collection in one pass.
/// Replaces the N-calls pattern in `_computeCollectionSizesAsync`.
List<CollectionStats> getAllCollectionStats() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllCollectionStats();

/// Aggregated per-collection stats returned in a single batch FFI call.
class CollectionStats {
  final String collectionId;
  final BigInt totalSize;
  final List<String> filePaths;

  const CollectionStats({
    required this.collectionId,
    required this.totalSize,
    required this.filePaths,
  });

  @override
  int get hashCode => collectionId.hashCode ^ totalSize.hashCode ^ filePaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionStats &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          totalSize == other.totalSize &&
          filePaths == other.filePaths;
}

class MediaCollection {
  final String id;
  final String title;
  final String folderPath;
  final String? folderId;
  final String? coverPath;
  final BigInt itemCount;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const MediaCollection({
    required this.id,
    required this.title,
    required this.folderPath,
    this.folderId,
    this.coverPath,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      folderPath.hashCode ^
      folderId.hashCode ^
      coverPath.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          folderPath == other.folderPath &&
          folderId == other.folderId &&
          coverPath == other.coverPath &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class MediaFolder {
  final String id;
  final String name;
  final PlatformInt64 createdAt;
  final int order;
  final String? parentId;

  const MediaFolder({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.order,
    this.parentId,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ createdAt.hashCode ^ order.hashCode ^ parentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaFolder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          order == other.order &&
          parentId == other.parentId;
}

class MediaItem {
  final String id;
  final String collectionId;
  final String title;
  final String filePath;
  final MediaKind kind;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final int? width;
  final int? height;
  final BigInt? durationMs;
  final int order;

  const MediaItem({
    required this.id,
    required this.collectionId,
    required this.title,
    required this.filePath,
    required this.kind,
    required this.fileSize,
    required this.modifiedAt,
    this.width,
    this.height,
    this.durationMs,
    required this.order,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      collectionId.hashCode ^
      title.hashCode ^
      filePath.hashCode ^
      kind.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          collectionId == other.collectionId &&
          title == other.title &&
          filePath == other.filePath &&
          kind == other.kind &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs &&
          order == other.order;
}

enum MediaKind { image, video, audio }
