// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_collection`, `convert_folder`, `convert_item`, `convert_kind`, `from_smart_folder`, `to_smart_folder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

List<MediaCollection> getAllMediaCollections() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllMediaCollections();

List<MediaFolder> getAllMediaFolders() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllMediaFolders();

List<MediaFolder> getChildMediaFolders({required String parentId}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionGetChildMediaFolders(parentId: parentId);

List<MediaItem> getMediaCollectionItems({required String collectionId}) =>
    RustLib.instance.api.crateApiMediaCollectionGetMediaCollectionItems(
      collectionId: collectionId,
    );

Future<MediaCollection> importMediaFolder({required String folderPath}) =>
    RustLib.instance.api.crateApiMediaCollectionImportMediaFolder(
      folderPath: folderPath,
    );

Future<List<MediaCollection>> scanMediaFolders({required String folderPath}) =>
    RustLib.instance.api.crateApiMediaCollectionScanMediaFolders(
      folderPath: folderPath,
    );

MediaFolder createMediaFolder({required String name}) =>
    RustLib.instance.api.crateApiMediaCollectionCreateMediaFolder(name: name);

MediaFolder createChildMediaFolder({
  required String name,
  required String parentId,
}) => RustLib.instance.api.crateApiMediaCollectionCreateChildMediaFolder(
  name: name,
  parentId: parentId,
);

bool renameMediaCollection({
  required String collectionId,
  required String title,
}) => RustLib.instance.api.crateApiMediaCollectionRenameMediaCollection(
  collectionId: collectionId,
  title: title,
);

bool moveMediaCollectionToFolder({
  required String collectionId,
  String? folderId,
}) => RustLib.instance.api.crateApiMediaCollectionMoveMediaCollectionToFolder(
  collectionId: collectionId,
  folderId: folderId,
);

bool renameMediaFolder({required String folderId, required String name}) =>
    RustLib.instance.api.crateApiMediaCollectionRenameMediaFolder(
      folderId: folderId,
      name: name,
    );

bool deleteMediaFolder({required String folderId}) => RustLib.instance.api
    .crateApiMediaCollectionDeleteMediaFolder(folderId: folderId);

bool deleteMediaCollection({required String collectionId}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionDeleteMediaCollection(collectionId: collectionId);

/// Generate (or serve from disk cache) a JPEG thumbnail for `file_path` at
/// `width` pixels wide.  Returns the path to the cached thumbnail, or `None`
/// on failure (unsupported format, decode error, etc.).
/// Resolution strategy: ffmpeg first (supports HEIC/AVIF), then pure-Rust
/// `image` crate as fallback.
String? ensureCoverThumbnail({required String filePath, required int width}) =>
    RustLib.instance.api.crateApiMediaCollectionEnsureCoverThumbnail(
      filePath: filePath,
      width: width,
    );

/// Return size + file-path list for every local collection in one pass.
/// Replaces the N-calls pattern in `_computeCollectionSizesAsync`.
List<CollectionStats> getAllCollectionStats() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllCollectionStats();

/// 从磁盘加载所有本地智能文件夹。
List<SmartFolderData> listSmartFolders() =>
    RustLib.instance.api.crateApiMediaCollectionListSmartFolders();

/// 将智能文件夹列表持久化到磁盘（全量覆盖）。
void saveAllSmartFolders({required List<SmartFolderData> folders}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionSaveAllSmartFolders(folders: folders);

/// 加载所有集合排序记录。
List<CollectionOrder> loadAllCollectionOrders() =>
    RustLib.instance.api.crateApiMediaCollectionLoadAllCollectionOrders();

/// 保存单条集合排序（ids 为空时删除该 key）。
void saveCollectionOrder({
  required String orderKey,
  required List<String> ids,
}) => RustLib.instance.api.crateApiMediaCollectionSaveCollectionOrder(
  orderKey: orderKey,
  ids: ids,
);

/// 加载收藏的集合 ID 列表。
List<String> loadMediaFavorites() =>
    RustLib.instance.api.crateApiMediaCollectionLoadMediaFavorites();

/// 保存收藏的集合 ID 列表。
void saveMediaFavorites({required List<String> ids}) =>
    RustLib.instance.api.crateApiMediaCollectionSaveMediaFavorites(ids: ids);

/// 将指定集合的文件物理迁移到 `<target_root>/<container_name>/` 子目录，
/// 并在数据库中重新注册。Dart 侧负责通过文件选择器获取 `target_root`，
/// 核心文件 I/O 和数据库操作在 Rust 层完成。
Future<TransferResult> transferCollections({
  required List<String> collectionIds,
  required String targetRoot,
  required String containerName,
}) => RustLib.instance.api.crateApiMediaCollectionTransferCollections(
  collectionIds: collectionIds,
  targetRoot: targetRoot,
  containerName: containerName,
);

/// 单条集合排序记录（orderKey → 有序 collectionId 列表）。
class CollectionOrder {
  final String key;
  final List<String> ids;

  const CollectionOrder({required this.key, required this.ids});

  @override
  int get hashCode => key.hashCode ^ ids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionOrder &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          ids == other.ids;
}

/// Aggregated per-collection stats returned in a single batch FFI call.
class CollectionStats {
  final String collectionId;
  final BigInt totalSize;
  final List<String> filePaths;

  const CollectionStats({
    required this.collectionId,
    required this.totalSize,
    required this.filePaths,
  });

  @override
  int get hashCode =>
      collectionId.hashCode ^ totalSize.hashCode ^ filePaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionStats &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          totalSize == other.totalSize &&
          filePaths == other.filePaths;
}

class MediaCollection {
  final String id;
  final String title;
  final String folderPath;
  final String? folderId;
  final String? coverPath;
  final BigInt itemCount;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const MediaCollection({
    required this.id,
    required this.title,
    required this.folderPath,
    this.folderId,
    this.coverPath,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      folderPath.hashCode ^
      folderId.hashCode ^
      coverPath.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          folderPath == other.folderPath &&
          folderId == other.folderId &&
          coverPath == other.coverPath &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class MediaFolder {
  final String id;
  final String name;
  final PlatformInt64 createdAt;
  final int order;
  final String? parentId;

  const MediaFolder({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.order,
    this.parentId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      order.hashCode ^
      parentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaFolder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          order == other.order &&
          parentId == other.parentId;
}

class MediaItem {
  final String id;
  final String collectionId;
  final String title;
  final String filePath;
  final MediaKind kind;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final int? width;
  final int? height;
  final BigInt? durationMs;
  final int order;

  const MediaItem({
    required this.id,
    required this.collectionId,
    required this.title,
    required this.filePath,
    required this.kind,
    required this.fileSize,
    required this.modifiedAt,
    this.width,
    this.height,
    this.durationMs,
    required this.order,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      collectionId.hashCode ^
      title.hashCode ^
      filePath.hashCode ^
      kind.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          collectionId == other.collectionId &&
          title == other.title &&
          filePath == other.filePath &&
          kind == other.kind &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs &&
          order == other.order;
}

enum MediaKind { image, video, audio }

/// 智能文件夹数据（供 FFI 传输，字段与 Dart 端 SmartFolder 保持一致）。
class SmartFolderData {
  final String id;
  final String name;
  final String regexPattern;

  /// 匹配目标字符串：collectionName | fileName
  final String regexTarget;

  /// 文件类型过滤字符串：all | images | videos
  final String fileTypeFilter;
  final List<String> targetFolderIds;

  const SmartFolderData({
    required this.id,
    required this.name,
    required this.regexPattern,
    required this.regexTarget,
    required this.fileTypeFilter,
    required this.targetFolderIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      regexPattern.hashCode ^
      regexTarget.hashCode ^
      fileTypeFilter.hashCode ^
      targetFolderIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmartFolderData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          regexPattern == other.regexPattern &&
          regexTarget == other.regexTarget &&
          fileTypeFilter == other.fileTypeFilter &&
          targetFolderIds == other.targetFolderIds;
}

/// 集合批量转移结果。
class TransferResult {
  final int successCount;
  final int failCount;

  const TransferResult({required this.successCount, required this.failCount});

  @override
  int get hashCode => successCount.hashCode ^ failCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferResult &&
          runtimeType == other.runtimeType &&
          successCount == other.successCount &&
          failCount == other.failCount;
}
