// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_collection`, `convert_folder`, `convert_item`, `convert_kind`, `convert_smart_folder`, `from_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

List<MediaCollection> getAllMediaCollections() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllMediaCollections();

List<MediaFolder> getAllMediaFolders() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllMediaFolders();

List<MediaFolder> getChildMediaFolders({required String parentId}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionGetChildMediaFolders(parentId: parentId);

List<MediaItem> getMediaCollectionItems({required String collectionId}) =>
    RustLib.instance.api.crateApiMediaCollectionGetMediaCollectionItems(
      collectionId: collectionId,
    );

Future<MediaCollection> importMediaFolder({required String folderPath}) =>
    RustLib.instance.api.crateApiMediaCollectionImportMediaFolder(
      folderPath: folderPath,
    );

Future<List<MediaCollection>> scanMediaFolders({required String folderPath}) =>
    RustLib.instance.api.crateApiMediaCollectionScanMediaFolders(
      folderPath: folderPath,
    );

MediaFolder createMediaFolder({required String name}) =>
    RustLib.instance.api.crateApiMediaCollectionCreateMediaFolder(name: name);

MediaFolder createChildMediaFolder({
  required String name,
  required String parentId,
}) => RustLib.instance.api.crateApiMediaCollectionCreateChildMediaFolder(
  name: name,
  parentId: parentId,
);

bool renameMediaCollection({
  required String collectionId,
  required String title,
}) => RustLib.instance.api.crateApiMediaCollectionRenameMediaCollection(
  collectionId: collectionId,
  title: title,
);

bool moveMediaCollectionToFolder({
  required String collectionId,
  String? folderId,
}) => RustLib.instance.api.crateApiMediaCollectionMoveMediaCollectionToFolder(
  collectionId: collectionId,
  folderId: folderId,
);

bool renameMediaFolder({required String folderId, required String name}) =>
    RustLib.instance.api.crateApiMediaCollectionRenameMediaFolder(
      folderId: folderId,
      name: name,
    );

bool deleteMediaFolder({required String folderId}) => RustLib.instance.api
    .crateApiMediaCollectionDeleteMediaFolder(folderId: folderId);

bool deleteMediaCollection({required String collectionId}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionDeleteMediaCollection(collectionId: collectionId);

/// Generate (or serve from disk cache) a JPEG thumbnail for `file_path` at
/// `width` pixels wide.  Returns the path to the cached thumbnail, or `None`
/// on failure (unsupported format, decode error, etc.).
/// Resolution strategy: ffmpeg first (supports HEIC/AVIF), then pure-Rust
/// `image` crate as fallback.
String? ensureCoverThumbnail({required String filePath, required int width}) =>
    RustLib.instance.api.crateApiMediaCollectionEnsureCoverThumbnail(
      filePath: filePath,
      width: width,
    );

/// Return size + file-path list for every local collection in one pass.
/// Replaces the N-calls pattern in `_computeCollectionSizesAsync`.
List<CollectionStats> getAllCollectionStats() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllCollectionStats();

/// Batch-check whether each file path exists on the local filesystem.
/// Returns a `Vec<bool>` aligned with the input — `true` means the file exists.
List<bool> checkPathsExist({required List<String> paths}) =>
    RustLib.instance.api.crateApiMediaCollectionCheckPathsExist(paths: paths);

/// Lightweight per-collection counts (no file paths), for polling file-count changes.
List<CollectionCount> getAllCollectionCounts() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllCollectionCounts();

/// Extract evenly-spaced scrub frames from a video file.
Future<List<String>> extractVideoScrubFrames({
  required String videoPath,
  required int frameCount,
}) => RustLib.instance.api.crateApiMediaCollectionExtractVideoScrubFrames(
  videoPath: videoPath,
  frameCount: frameCount,
);

/// 删除单个媒体文件的物理文件，然后重新导入集合目录以同步数据库。
bool deleteMediaItemFile({required String itemFilePath}) => RustLib.instance.api
    .crateApiMediaCollectionDeleteMediaItemFile(itemFilePath: itemFilePath);

/// 删除集合内所有媒体文件的物理文件，返回已删除的文件数量。
int deleteCollectionLocalFiles({required String collectionId}) =>
    RustLib.instance.api.crateApiMediaCollectionDeleteCollectionLocalFiles(
      collectionId: collectionId,
    );

/// 将集合物理转移到目标目录。
Future<int> transferCollections({
  required List<String> collectionIds,
  required String targetDir,
}) => RustLib.instance.api.crateApiMediaCollectionTransferCollections(
  collectionIds: collectionIds,
  targetDir: targetDir,
);

/// 打开文件所在目录（跨平台）。
Future<void> openInFileManager({required String filePath}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionOpenInFileManager(filePath: filePath);

/// 获取所有集合排序记录。
List<(String, List<String>)> getAllCollectionOrders() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllCollectionOrders();

/// 保存集合排序。
void saveCollectionOrder({
  required String orderKey,
  required List<String> ids,
}) => RustLib.instance.api.crateApiMediaCollectionSaveCollectionOrder(
  orderKey: orderKey,
  ids: ids,
);

/// 获取收藏集合 ID 列表。
List<String> getFavoriteCollectionIds() =>
    RustLib.instance.api.crateApiMediaCollectionGetFavoriteCollectionIds();

/// 保存收藏集合 ID 列表。
void saveFavoriteCollectionIds({required List<String> ids}) => RustLib
    .instance
    .api
    .crateApiMediaCollectionSaveFavoriteCollectionIds(ids: ids);

List<SmartFolderInfo> getAllSmartFolders() =>
    RustLib.instance.api.crateApiMediaCollectionGetAllSmartFolders();

SmartFolderInfo createSmartFolder({
  required String name,
  required String regexPattern,
  required List<String> keywords,
  required String regexTarget,
  required String fileTypeFilter,
  required List<String> targetFolderIds,
}) => RustLib.instance.api.crateApiMediaCollectionCreateSmartFolder(
  name: name,
  regexPattern: regexPattern,
  keywords: keywords,
  regexTarget: regexTarget,
  fileTypeFilter: fileTypeFilter,
  targetFolderIds: targetFolderIds,
);

SmartFolderInfo updateSmartFolder({
  required String id,
  required String name,
  required String regexPattern,
  required List<String> keywords,
  required String regexTarget,
  required String fileTypeFilter,
  required List<String> targetFolderIds,
}) => RustLib.instance.api.crateApiMediaCollectionUpdateSmartFolder(
  id: id,
  name: name,
  regexPattern: regexPattern,
  keywords: keywords,
  regexTarget: regexTarget,
  fileTypeFilter: fileTypeFilter,
  targetFolderIds: targetFolderIds,
);

bool deleteSmartFolder({required String id}) =>
    RustLib.instance.api.crateApiMediaCollectionDeleteSmartFolder(id: id);

/// FFI version of [media_collection::CollectionCount].
class CollectionCount {
  final String collectionId;
  final int itemCount;
  final BigInt totalSize;

  const CollectionCount({
    required this.collectionId,
    required this.itemCount,
    required this.totalSize,
  });

  @override
  int get hashCode =>
      collectionId.hashCode ^ itemCount.hashCode ^ totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionCount &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          itemCount == other.itemCount &&
          totalSize == other.totalSize;
}

/// Aggregated per-collection stats returned in a single batch FFI call.
class CollectionStats {
  final String collectionId;
  final BigInt totalSize;
  final List<String> filePaths;

  const CollectionStats({
    required this.collectionId,
    required this.totalSize,
    required this.filePaths,
  });

  @override
  int get hashCode =>
      collectionId.hashCode ^ totalSize.hashCode ^ filePaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionStats &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          totalSize == other.totalSize &&
          filePaths == other.filePaths;
}

class MediaCollection {
  final String id;
  final String title;
  final String folderPath;
  final String? folderId;
  final String? coverPath;
  final BigInt itemCount;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const MediaCollection({
    required this.id,
    required this.title,
    required this.folderPath,
    this.folderId,
    this.coverPath,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      folderPath.hashCode ^
      folderId.hashCode ^
      coverPath.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          folderPath == other.folderPath &&
          folderId == other.folderId &&
          coverPath == other.coverPath &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class MediaFolder {
  final String id;
  final String name;
  final PlatformInt64 createdAt;
  final int order;
  final String? parentId;

  const MediaFolder({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.order,
    this.parentId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      order.hashCode ^
      parentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaFolder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          order == other.order &&
          parentId == other.parentId;
}

class MediaItem {
  final String id;
  final String collectionId;
  final String title;
  final String filePath;
  final MediaKind kind;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final int? width;
  final int? height;
  final BigInt? durationMs;
  final int order;

  const MediaItem({
    required this.id,
    required this.collectionId,
    required this.title,
    required this.filePath,
    required this.kind,
    required this.fileSize,
    required this.modifiedAt,
    this.width,
    this.height,
    this.durationMs,
    required this.order,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      collectionId.hashCode ^
      title.hashCode ^
      filePath.hashCode ^
      kind.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          collectionId == other.collectionId &&
          title == other.title &&
          filePath == other.filePath &&
          kind == other.kind &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs &&
          order == other.order;
}

enum MediaKind { image, video, audio }

/// 文件类型过滤
enum SmartFolderFileType { all, images, videos }

/// 智能文件夹
class SmartFolderInfo {
  final String id;
  final String name;
  final String regexPattern;
  final List<String> keywords;
  final SmartFolderRegexTarget regexTarget;
  final SmartFolderFileType fileTypeFilter;
  final List<String> targetFolderIds;

  const SmartFolderInfo({
    required this.id,
    required this.name,
    required this.regexPattern,
    required this.keywords,
    required this.regexTarget,
    required this.fileTypeFilter,
    required this.targetFolderIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      regexPattern.hashCode ^
      keywords.hashCode ^
      regexTarget.hashCode ^
      fileTypeFilter.hashCode ^
      targetFolderIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmartFolderInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          regexPattern == other.regexPattern &&
          keywords == other.keywords &&
          regexTarget == other.regexTarget &&
          fileTypeFilter == other.fileTypeFilter &&
          targetFolderIds == other.targetFolderIds;
}

/// 正则匹配目标
enum SmartFolderRegexTarget { collectionName, fileName }
