// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ffmpeg.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModuleDownloader>>
abstract class ModuleDownloader implements RustOpaqueInterface {
  /// 下载并安装模块
  Future<PathBuf> downloadModule({required ModuleConfig config});

  /// 获取可执行文件路径
  Future<PathBuf> getExecutablePath({
    required String moduleName,
    required String executableName,
  });

  /// 获取模块安装路径
  Future<PathBuf> getModulePath({required String moduleName});

  /// 获取模块版本（通过执行 --version 命令）
  Future<String> getModuleVersion({
    required String moduleName,
    required String executableName,
  });

  /// 检查模块是否已安装
  Future<bool> isModuleInstalled({
    required String moduleName,
    required String executableName,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建模块下载器
  static Future<ModuleDownloader> newInstance({required PathBuf installDir}) =>
      RustLib.instance.api.crateApiModuleDownloaderModuleDownloaderNew(
        installDir: installDir,
      );

  /// 删除模块
  Future<void> removeModule({required String moduleName});
}

/// 模块下载配置
class ModuleConfig {
  final String name;
  final String windowsUrl;
  final String macosUrl;
  final String executableName;

  const ModuleConfig({
    required this.name,
    required this.windowsUrl,
    required this.macosUrl,
    required this.executableName,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      windowsUrl.hashCode ^
      macosUrl.hashCode ^
      executableName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          windowsUrl == other.windowsUrl &&
          macosUrl == other.macosUrl &&
          executableName == other.executableName;
}
