// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'module_manager.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 检查模块是否已安装
bool isModuleInstalled({
  required String installDir,
  required String moduleName,
  required ModuleType moduleType,
  required String fileName,
}) => RustLib.instance.api.crateApiModuleApiIsModuleInstalled(
  installDir: installDir,
  moduleName: moduleName,
  moduleType: moduleType,
  fileName: fileName,
);

/// 获取已安装模块的版本
String? getInstalledModuleVersion({
  required String installDir,
  required String moduleName,
}) => RustLib.instance.api.crateApiModuleApiGetInstalledModuleVersion(
  installDir: installDir,
  moduleName: moduleName,
);

/// 检查模块是否需要更新
bool checkModuleNeedsUpdate({
  required String installDir,
  required String moduleName,
  required ModuleType moduleType,
  required String currentVersion,
  required String windowsUrl,
  required String macosUrl,
  required String fileName,
}) => RustLib.instance.api.crateApiModuleApiCheckModuleNeedsUpdate(
  installDir: installDir,
  moduleName: moduleName,
  moduleType: moduleType,
  currentVersion: currentVersion,
  windowsUrl: windowsUrl,
  macosUrl: macosUrl,
  fileName: fileName,
);

/// 下载模块
Future<String> downloadModule({
  required String installDir,
  required String moduleName,
  required ModuleType moduleType,
  required String version,
  required String windowsUrl,
  required String macosUrl,
  required String fileName,
}) => RustLib.instance.api.crateApiModuleApiDownloadModule(
  installDir: installDir,
  moduleName: moduleName,
  moduleType: moduleType,
  version: version,
  windowsUrl: windowsUrl,
  macosUrl: macosUrl,
  fileName: fileName,
);

/// 下载 Capture Proxy 模块（便捷方法）
Future<String> downloadCaptureProxyModule({
  required String installDir,
  required String version,
  required String windowsUrl,
  required String macosUrl,
}) => RustLib.instance.api.crateApiModuleApiDownloadCaptureProxyModule(
  installDir: installDir,
  version: version,
  windowsUrl: windowsUrl,
  macosUrl: macosUrl,
);

/// 下载 FFmpeg 模块（便捷方法）
Future<String> downloadFfmpegModule({
  required String installDir,
  required String version,
  required String windowsUrl,
  required String macosUrl,
}) => RustLib.instance.api.crateApiModuleApiDownloadFfmpegModule(
  installDir: installDir,
  version: version,
  windowsUrl: windowsUrl,
  macosUrl: macosUrl,
);

/// 获取模块文件路径
String getModuleFilePath({
  required String installDir,
  required String moduleName,
  required ModuleType moduleType,
  required String fileName,
}) => RustLib.instance.api.crateApiModuleApiGetModuleFilePath(
  installDir: installDir,
  moduleName: moduleName,
  moduleType: moduleType,
  fileName: fileName,
);

/// 检查所有模块状态
Future<List<ModuleStatus>> checkAllModulesStatus({
  required String installDir,
  required String captureProxyVersion,
  required String captureProxyWindowsUrl,
  required String captureProxyMacosUrl,
  required String ffmpegVersion,
  required String ffmpegWindowsUrl,
  required String ffmpegMacosUrl,
}) => RustLib.instance.api.crateApiModuleApiCheckAllModulesStatus(
  installDir: installDir,
  captureProxyVersion: captureProxyVersion,
  captureProxyWindowsUrl: captureProxyWindowsUrl,
  captureProxyMacosUrl: captureProxyMacosUrl,
  ffmpegVersion: ffmpegVersion,
  ffmpegWindowsUrl: ffmpegWindowsUrl,
  ffmpegMacosUrl: ffmpegMacosUrl,
);

/// 批量检查模块状态
class ModuleStatus {
  final String name;
  final bool installed;
  final String? currentVersion;
  final bool needsUpdate;

  const ModuleStatus({
    required this.name,
    required this.installed,
    this.currentVersion,
    required this.needsUpdate,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      installed.hashCode ^
      currentVersion.hashCode ^
      needsUpdate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          installed == other.installed &&
          currentVersion == other.currentVersion &&
          needsUpdate == other.needsUpdate;
}
