// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_loaded_async`, `ensure_loaded`, `get_module`, `load_module`, `new`, `unload_module`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CModuleInfo`, `MODULE_MANAGER`, `ModuleInfo`, `ModuleManager`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `fmt`, `initialize`

/// 下载并加载 capture_proxy 模块
Future<String> downloadCaptureProxyModule({
  required String windowsUrl,
  required String macosUrl,
  required String installDir,
}) => RustLib.instance.api.crateApiModuleLoaderDownloadCaptureProxyModule(
  windowsUrl: windowsUrl,
  macosUrl: macosUrl,
  installDir: installDir,
);

/// 检查 capture_proxy 模块是否已下载
Future<bool> isCaptureProxyDownloaded({required String installDir}) => RustLib
    .instance
    .api
    .crateApiModuleLoaderIsCaptureProxyDownloaded(installDir: installDir);

/// Capture Proxy 模块包装器（不对外暴露给 Dart）
class CaptureProxyModule {
  const CaptureProxyModule();

  /// 清除捕获的数据
  static Future<void> clearData({required String installDir}) => RustLib
      .instance
      .api
      .crateApiModuleLoaderCaptureProxyModuleClearData(installDir: installDir);

  /// 获取捕获的视频列表
  static Future<List<String>> getVideos({required String installDir}) => RustLib
      .instance
      .api
      .crateApiModuleLoaderCaptureProxyModuleGetVideos(installDir: installDir);

  /// 安装 CA 证书
  static Future<void> installCertificate({
    required String password,
    required String installDir,
  }) => RustLib.instance.api
      .crateApiModuleLoaderCaptureProxyModuleInstallCertificate(
        password: password,
        installDir: installDir,
      );

  /// 检查证书是否已安装
  static Future<bool> isCertificateInstalled({required String installDir}) =>
      RustLib.instance.api
          .crateApiModuleLoaderCaptureProxyModuleIsCertificateInstalled(
            installDir: installDir,
          );

  /// 检查代理是否运行
  static Future<bool> isRunning({required String installDir}) => RustLib
      .instance
      .api
      .crateApiModuleLoaderCaptureProxyModuleIsRunning(installDir: installDir);

  /// 启动代理
  static Future<String> start({
    required int port,
    required String installDir,
  }) => RustLib.instance.api.crateApiModuleLoaderCaptureProxyModuleStart(
    port: port,
    installDir: installDir,
  );

  /// 停止代理
  static Future<String> stop({required String installDir}) => RustLib
      .instance
      .api
      .crateApiModuleLoaderCaptureProxyModuleStop(installDir: installDir);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureProxyModule && runtimeType == other.runtimeType;
}
