// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_metadata_path`, `save_module_metadata`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ModuleConfigs`, `ModuleMetadata`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `capture_proxy`, `download_module`, `ffmpeg`, `get_download_url`, `get_installed_version`, `get_module_dir`, `get_module_file_path`, `get_module_metadata`, `get_modules_dir`, `is_module_installed`, `needs_update`

/// 模块类型
enum ModuleType {
  /// 动态库模块（.dll / .dylib / .so）
  library_,

  /// 可执行程序模块（.exe / 无扩展名）
  executable,
}
