// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_cue_sheet`, `convert_eq_preset`, `convert_item`, `convert_playlist`, `convert_record`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlayMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 初始化音乐播放器数据库
void musicInitializeDb() =>
    RustLib.instance.api.crateApiMusicPlayerMusicInitializeDb();

/// 获取所有播放列表
List<Playlist> getAllPlaylists() =>
    RustLib.instance.api.crateApiMusicPlayerGetAllPlaylists();

/// 创建播放列表
Playlist createPlaylist({required String name}) =>
    RustLib.instance.api.crateApiMusicPlayerCreatePlaylist(name: name);

/// 确保默认播放列表存在
Playlist ensureDefaultPlaylist() =>
    RustLib.instance.api.crateApiMusicPlayerEnsureDefaultPlaylist();

/// 重命名播放列表
bool renamePlaylist({required String playlistId, required String name}) =>
    RustLib.instance.api.crateApiMusicPlayerRenamePlaylist(
      playlistId: playlistId,
      name: name,
    );

/// 删除播放列表
bool deletePlaylist({required String playlistId}) => RustLib.instance.api
    .crateApiMusicPlayerDeletePlaylist(playlistId: playlistId);

/// 获取播放列表内的音乐条目
List<MusicItem> getPlaylistItems({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerGetPlaylistItems(playlistId: playlistId);

/// 获取所有音乐条目
List<MusicItem> getAllMusicItems() =>
    RustLib.instance.api.crateApiMusicPlayerGetAllMusicItems();

/// 导入音乐文件夹到播放列表
Future<List<MusicItem>> importMusicFolder({
  required String playlistId,
  required String folderPath,
}) => RustLib.instance.api.crateApiMusicPlayerImportMusicFolder(
  playlistId: playlistId,
  folderPath: folderPath,
);

/// 导入单个音乐文件
MusicItem importMusicFile({
  required String playlistId,
  required String filePath,
}) => RustLib.instance.api.crateApiMusicPlayerImportMusicFile(
  playlistId: playlistId,
  filePath: filePath,
);

/// 批量导入音乐文件路径
Future<List<MusicItem>> importMusicPaths({
  required String playlistId,
  required List<String> paths,
}) => RustLib.instance.api.crateApiMusicPlayerImportMusicPaths(
  playlistId: playlistId,
  paths: paths,
);

/// 删除音乐条目
bool deleteMusicItem({required String itemId}) =>
    RustLib.instance.api.crateApiMusicPlayerDeleteMusicItem(itemId: itemId);

/// 清空播放列表内所有音乐
int clearPlaylistItems({required String playlistId}) => RustLib.instance.api
    .crateApiMusicPlayerClearPlaylistItems(playlistId: playlistId);

/// 更新音乐条目信息
bool updateMusicItem({
  required String itemId,
  String? title,
  String? artist,
  String? album,
  bool? isFavorite,
}) => RustLib.instance.api.crateApiMusicPlayerUpdateMusicItem(
  itemId: itemId,
  title: title,
  artist: artist,
  album: album,
  isFavorite: isFavorite,
);

/// 保存播放列表排序
void savePlaylistOrder({
  required String playlistId,
  required List<String> itemIds,
}) => RustLib.instance.api.crateApiMusicPlayerSavePlaylistOrder(
  playlistId: playlistId,
  itemIds: itemIds,
);

/// 解析 CUE 文件
CueSheetInfo parseCueFile({required String cuePath}) =>
    RustLib.instance.api.crateApiMusicPlayerParseCueFile(cuePath: cuePath);

/// 获取最近播放记录
List<PlayRecordInfo> getRecentPlayed({required int limit}) =>
    RustLib.instance.api.crateApiMusicPlayerGetRecentPlayed(limit: limit);

/// 记录播放
PlayRecordInfo recordPlay({required String musicId}) =>
    RustLib.instance.api.crateApiMusicPlayerRecordPlay(musicId: musicId);

/// 获取收藏的音乐
List<MusicItem> getFavoriteItems() =>
    RustLib.instance.api.crateApiMusicPlayerGetFavoriteItems();

/// 切换收藏状态
bool toggleFavorite({required String itemId}) =>
    RustLib.instance.api.crateApiMusicPlayerToggleFavorite(itemId: itemId);

/// 获取均衡器预设
List<EqualizerPresetInfo> getEqPresets() =>
    RustLib.instance.api.crateApiMusicPlayerGetEqPresets();

/// 保存均衡器预设
EqualizerPresetInfo saveEqPreset({
  required String name,
  required List<double> bands,
}) => RustLib.instance.api.crateApiMusicPlayerSaveEqPreset(
  name: name,
  bands: bands,
);

/// 删除均衡器预设
bool deleteEqPreset({required String presetId}) =>
    RustLib.instance.api.crateApiMusicPlayerDeleteEqPreset(presetId: presetId);

/// 生成音乐封面缩略图
String? ensureMusicCoverThumbnail({
  required String filePath,
  required int width,
}) => RustLib.instance.api.crateApiMusicPlayerEnsureMusicCoverThumbnail(
  filePath: filePath,
  width: width,
);

/// 批量提取封面（后台调用，不阻塞导入流程）
Future<BigInt> batchExtractCovers({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerBatchExtractCovers(playlistId: playlistId);

class CueSheetInfo {
  final String? title;
  final String? performer;
  final String audioFile;
  final List<CueTrackInfo> tracks;

  const CueSheetInfo({
    this.title,
    this.performer,
    required this.audioFile,
    required this.tracks,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      performer.hashCode ^
      audioFile.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueSheetInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          performer == other.performer &&
          audioFile == other.audioFile &&
          tracks == other.tracks;
}

class CueTrackInfo {
  final String title;
  final String? performer;
  final BigInt startMs;
  final BigInt? endMs;
  final int trackNumber;

  const CueTrackInfo({
    required this.title,
    this.performer,
    required this.startMs,
    this.endMs,
    required this.trackNumber,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      performer.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      trackNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueTrackInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          performer == other.performer &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          trackNumber == other.trackNumber;
}

class EqualizerPresetInfo {
  final String id;
  final String name;
  final Float32List bands;
  final bool isBuiltin;

  const EqualizerPresetInfo({
    required this.id,
    required this.name,
    required this.bands,
    required this.isBuiltin,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ bands.hashCode ^ isBuiltin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqualizerPresetInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          bands == other.bands &&
          isBuiltin == other.isBuiltin;
}

class MusicItem {
  final String id;
  final String playlistId;
  final String title;
  final String? artist;
  final String? album;
  final String filePath;
  final BigInt? durationMs;
  final int? trackNumber;
  final int? discNumber;
  final int? year;
  final String? genre;
  final String? coverPath;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final int order;
  final bool isFavorite;

  const MusicItem({
    required this.id,
    required this.playlistId,
    required this.title,
    this.artist,
    this.album,
    required this.filePath,
    this.durationMs,
    this.trackNumber,
    this.discNumber,
    this.year,
    this.genre,
    this.coverPath,
    required this.fileSize,
    required this.modifiedAt,
    required this.order,
    required this.isFavorite,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      playlistId.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      filePath.hashCode ^
      durationMs.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      year.hashCode ^
      genre.hashCode ^
      coverPath.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      order.hashCode ^
      isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MusicItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          playlistId == other.playlistId &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          filePath == other.filePath &&
          durationMs == other.durationMs &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          year == other.year &&
          genre == other.genre &&
          coverPath == other.coverPath &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          order == other.order &&
          isFavorite == other.isFavorite;
}

class PlayRecordInfo {
  final String id;
  final String musicId;
  final PlatformInt64 playedAt;
  final int playCount;

  const PlayRecordInfo({
    required this.id,
    required this.musicId,
    required this.playedAt,
    required this.playCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ musicId.hashCode ^ playedAt.hashCode ^ playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayRecordInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          musicId == other.musicId &&
          playedAt == other.playedAt &&
          playCount == other.playCount;
}

class Playlist {
  final String id;
  final String name;
  final String? coverPath;
  final BigInt itemCount;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final bool isDefault;

  const Playlist({
    required this.id,
    required this.name,
    this.coverPath,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
    required this.isDefault,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      coverPath.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          coverPath == other.coverPath &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          isDefault == other.isDefault;
}
