// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dart:io';

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_downsample_waveform`, `_read_waveform_cache`, `_waveform_cache_path`, `_write_waveform_cache`, `convert_cue_sheet`, `convert_eq_preset`, `convert_folder`, `convert_item`, `convert_playlist`, `convert_record`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlayMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 初始化音乐播放器数据库
void musicInitializeDb() =>
    RustLib.instance.api.crateApiMusicPlayerMusicInitializeDb();

/// 获取所有播放列表
List<Playlist> getAllPlaylists() =>
    RustLib.instance.api.crateApiMusicPlayerGetAllPlaylists();

/// 创建播放列表
Playlist createPlaylist({required String name}) =>
    RustLib.instance.api.crateApiMusicPlayerCreatePlaylist(name: name);

/// 在指定目录下创建播放列表
Playlist createPlaylistInFolder({required String name, String? folderId}) =>
    RustLib.instance.api.crateApiMusicPlayerCreatePlaylistInFolder(
      name: name,
      folderId: folderId,
    );

/// 获取指定目录下的播放列表
List<Playlist> getPlaylistsByFolder({String? folderId}) => RustLib.instance.api
    .crateApiMusicPlayerGetPlaylistsByFolder(folderId: folderId);

/// 确保默认播放列表存在
Playlist ensureDefaultPlaylist() =>
    RustLib.instance.api.crateApiMusicPlayerEnsureDefaultPlaylist();

/// 重命名播放列表
bool renamePlaylist({required String playlistId, required String name}) =>
    RustLib.instance.api.crateApiMusicPlayerRenamePlaylist(
      playlistId: playlistId,
      name: name,
    );

/// 删除播放列表
bool deletePlaylist({required String playlistId}) => RustLib.instance.api
    .crateApiMusicPlayerDeletePlaylist(playlistId: playlistId);

/// 获取播放列表内的音乐条目
List<MusicItem> getPlaylistItems({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerGetPlaylistItems(playlistId: playlistId);

/// 获取所有音乐条目
List<MusicItem> getAllMusicItems() =>
    RustLib.instance.api.crateApiMusicPlayerGetAllMusicItems();

/// 导入音乐文件夹到播放列表
Future<List<MusicItem>> importMusicFolder({
  required String playlistId,
  required String folderPath,
}) => RustLib.instance.api.crateApiMusicPlayerImportMusicFolder(
  playlistId: playlistId,
  folderPath: folderPath,
);

/// 导入单个音乐文件
MusicItem importMusicFile({
  required String playlistId,
  required String filePath,
}) => RustLib.instance.api.crateApiMusicPlayerImportMusicFile(
  playlistId: playlistId,
  filePath: filePath,
);

/// 批量导入音乐文件路径
Future<List<MusicItem>> importMusicPaths({
  required String playlistId,
  required List<String> paths,
}) => RustLib.instance.api.crateApiMusicPlayerImportMusicPaths(
  playlistId: playlistId,
  paths: paths,
);

/// 删除音乐条目
bool deleteMusicItem({required String itemId}) =>
    RustLib.instance.api.crateApiMusicPlayerDeleteMusicItem(itemId: itemId);

/// 清空播放列表内所有音乐
int clearPlaylistItems({required String playlistId}) => RustLib.instance.api
    .crateApiMusicPlayerClearPlaylistItems(playlistId: playlistId);

/// 更新音乐条目信息
bool updateMusicItem({
  required String itemId,
  String? title,
  String? artist,
  String? album,
  bool? isFavorite,
}) => RustLib.instance.api.crateApiMusicPlayerUpdateMusicItem(
  itemId: itemId,
  title: title,
  artist: artist,
  album: album,
  isFavorite: isFavorite,
);

/// 保存播放列表排序
void savePlaylistOrder({
  required String playlistId,
  required List<String> itemIds,
}) => RustLib.instance.api.crateApiMusicPlayerSavePlaylistOrder(
  playlistId: playlistId,
  itemIds: itemIds,
);

/// 解析 CUE 文件
CueSheetInfo parseCueFile({required String cuePath}) =>
    RustLib.instance.api.crateApiMusicPlayerParseCueFile(cuePath: cuePath);

/// 获取最近播放记录
List<PlayRecordInfo> getRecentPlayed({required int limit}) =>
    RustLib.instance.api.crateApiMusicPlayerGetRecentPlayed(limit: limit);

/// 记录播放
PlayRecordInfo recordPlay({required String musicId}) =>
    RustLib.instance.api.crateApiMusicPlayerRecordPlay(musicId: musicId);

/// 获取收藏的音乐
List<MusicItem> getFavoriteItems() =>
    RustLib.instance.api.crateApiMusicPlayerGetFavoriteItems();

/// 切换收藏状态
bool toggleFavorite({required String itemId}) =>
    RustLib.instance.api.crateApiMusicPlayerToggleFavorite(itemId: itemId);

/// 获取均衡器预设
List<EqualizerPresetInfo> getEqPresets() =>
    RustLib.instance.api.crateApiMusicPlayerGetEqPresets();

/// 保存均衡器预设
EqualizerPresetInfo saveEqPreset({
  required String name,
  required List<double> bands,
}) => RustLib.instance.api.crateApiMusicPlayerSaveEqPreset(
  name: name,
  bands: bands,
);

/// 删除均衡器预设
bool deleteEqPreset({required String presetId}) =>
    RustLib.instance.api.crateApiMusicPlayerDeleteEqPreset(presetId: presetId);

/// 生成音乐封面缩略图
String? ensureMusicCoverThumbnail({
  required String filePath,
  required int width,
}) => RustLib.instance.api.crateApiMusicPlayerEnsureMusicCoverThumbnail(
  filePath: filePath,
  width: width,
);

/// 批量提取封面（后台调用，不阻塞导入流程）
Future<BigInt> batchExtractCovers({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerBatchExtractCovers(playlistId: playlistId);

/// 修复已有音乐条目的缺失元数据（时长、标签等）
Future<BigInt> repairMissingMetadata({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerRepairMissingMetadata(playlistId: playlistId);

/// 获取所有目录
List<FolderInfo> getAllFolders() =>
    RustLib.instance.api.crateApiMusicPlayerGetAllFolders();

/// 获取指定父目录下的子目录
List<FolderInfo> getSubFolders({String? parentId}) =>
    RustLib.instance.api.crateApiMusicPlayerGetSubFolders(parentId: parentId);

/// 创建目录（最多三级）
FolderInfo createFolder({required String name, String? parentId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerCreateFolder(name: name, parentId: parentId);

/// 重命名目录
bool renameFolder({required String folderId, required String name}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerRenameFolder(folderId: folderId, name: name);

/// 删除目录（级联删除子目录和关联的播放列表）
bool deleteFolder({required String folderId}) =>
    RustLib.instance.api.crateApiMusicPlayerDeleteFolder(folderId: folderId);

/// 更新目录信息（封面、标签、作者等）
bool updateFolder({
  required String folderId,
  String? name,
  String? coverPath,
  String? tags,
  String? author,
}) => RustLib.instance.api.crateApiMusicPlayerUpdateFolder(
  folderId: folderId,
  name: name,
  coverPath: coverPath,
  tags: tags,
  author: author,
);

/// 递增目录播放次数
bool incrementFolderPlayCount({required String folderId}) => RustLib
    .instance
    .api
    .crateApiMusicPlayerIncrementFolderPlayCount(folderId: folderId);

/// 提取音频文件的波形数据（用于可视化）
/// 返回降采样后的振幅数组（0.0~1.0），samples 指定返回的采样点数
Future<Float64List> extractWaveform({
  required String audioFilePath,
  required int samples,
}) => RustLib.instance.api.crateApiMusicPlayerExtractWaveform(
  audioFilePath: audioFilePath,
  samples: samples,
);

/// 扫描文件夹路径映射（返回树形结构，不限制文件类型，不限深度）
/// 注意：此函数在 Dart 端实现，因为 frb 代码生成需要 libclang 环境
PathMappingNodeInfo scanPathMapping({required String dirPath}) {
  return _scanPathMappingDart(dirPath);
}

/// Dart 端实现的路径映射扫描
PathMappingNodeInfo _scanPathMappingDart(String dirPath) {
  final dir = Directory(dirPath);
  if (!dir.existsSync()) {
    throw Exception('目录不存在: $dirPath');
  }
  return _scanDirectory(dir);
}

PathMappingNodeInfo _scanDirectory(Directory dir) {
  final name = dir.path.split(Platform.pathSeparator).last;
  final children = <PathMappingNodeInfo>[];
  bool hasAudio = false;

  final entries = dir.listSync().toList();
  entries.sort((a, b) {
    final aIsDir = a is Directory;
    final bIsDir = b is Directory;
    if (aIsDir && !bIsDir) return -1;
    if (!aIsDir && bIsDir) return 1;
    return a.path.split(Platform.pathSeparator).last
        .compareTo(b.path.split(Platform.pathSeparator).last);
  });

  for (final entity in entries) {
    final entityName = entity.path.split(Platform.pathSeparator).last;
    // 跳过隐藏文件/目录
    if (entityName.startsWith('.')) continue;

    if (entity is Directory) {
      final child = _scanDirectory(entity);
      children.add(child);
      if (child.hasAudio) hasAudio = true;
    } else if (entity is File) {
      final nodeType = _classifyFile(entityName);
      final isAudio = nodeType == PathMappingNodeType.audioFile;
      if (isAudio) hasAudio = true;
      int? fileSize;
      try {
        fileSize = entity.lengthSync();
      } catch (_) {}
      children.add(PathMappingNodeInfo(
        name: entityName,
        path: entity.path,
        nodeType: nodeType,
        fileSize: fileSize,
        children: const [],
        hasAudio: isAudio,
      ));
    }
  }

  return PathMappingNodeInfo(
    name: name,
    path: dir.path,
    nodeType: PathMappingNodeType.directory,
    fileSize: null,
    children: children,
    hasAudio: hasAudio,
  );
}

PathMappingNodeType _classifyFile(String fileName) {
  final ext = fileName.contains('.') ? fileName.split('.').last.toLowerCase() : '';
  const audioExts = {'mp3', 'flac', 'aac', 'm4a', 'ogg', 'opus', 'wav', 'wma', 'ape', 'aiff', 'alac', 'wv', 'tta', 'dsd', 'dsf', 'dff'};
  const imageExts = {'jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg', 'tiff', 'tif', 'ico'};
  if (audioExts.contains(ext)) return PathMappingNodeType.audioFile;
  if (ext == 'cue') return PathMappingNodeType.cueFile;
  if (imageExts.contains(ext)) return PathMappingNodeType.imageFile;
  return PathMappingNodeType.otherFile;
}

class CueSheetInfo {
  final String? title;
  final String? performer;
  final String audioFile;
  final List<CueTrackInfo> tracks;

  const CueSheetInfo({
    this.title,
    this.performer,
    required this.audioFile,
    required this.tracks,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      performer.hashCode ^
      audioFile.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueSheetInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          performer == other.performer &&
          audioFile == other.audioFile &&
          tracks == other.tracks;
}

class CueTrackInfo {
  final String title;
  final String? performer;
  final BigInt startMs;
  final BigInt? endMs;
  final int trackNumber;

  const CueTrackInfo({
    required this.title,
    this.performer,
    required this.startMs,
    this.endMs,
    required this.trackNumber,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      performer.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      trackNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueTrackInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          performer == other.performer &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          trackNumber == other.trackNumber;
}

class EqualizerPresetInfo {
  final String id;
  final String name;
  final Float32List bands;
  final bool isBuiltin;

  const EqualizerPresetInfo({
    required this.id,
    required this.name,
    required this.bands,
    required this.isBuiltin,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ bands.hashCode ^ isBuiltin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqualizerPresetInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          bands == other.bands &&
          isBuiltin == other.isBuiltin;
}

/// 目录节点（最多三级）
class FolderInfo {
  final String id;
  final String name;

  /// 父目录 ID，根级为 None
  final String? parentId;

  /// 目录层级：1=根级，2=二级，3=三级
  final int level;

  /// 目录封面路径
  final String? coverPath;

  /// 标签（逗号分隔）
  final String? tags;

  /// 作者/演唱者
  final String? author;

  /// 目录下所有音乐的累计播放次数
  final int playCount;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const FolderInfo({
    required this.id,
    required this.name,
    this.parentId,
    required this.level,
    this.coverPath,
    this.tags,
    this.author,
    required this.playCount,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      level.hashCode ^
      coverPath.hashCode ^
      tags.hashCode ^
      author.hashCode ^
      playCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          level == other.level &&
          coverPath == other.coverPath &&
          tags == other.tags &&
          author == other.author &&
          playCount == other.playCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class MusicItem {
  final String id;
  final String playlistId;
  final String title;
  final String? artist;
  final String? album;
  final String filePath;
  final BigInt? durationMs;
  final int? trackNumber;
  final int? discNumber;
  final int? year;
  final String? genre;
  final String? coverPath;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final int order;
  final bool isFavorite;

  /// 是否有对应的 .cue 文件
  final bool hasCue;

  const MusicItem({
    required this.id,
    required this.playlistId,
    required this.title,
    this.artist,
    this.album,
    required this.filePath,
    this.durationMs,
    this.trackNumber,
    this.discNumber,
    this.year,
    this.genre,
    this.coverPath,
    required this.fileSize,
    required this.modifiedAt,
    required this.order,
    required this.isFavorite,
    required this.hasCue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      playlistId.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      filePath.hashCode ^
      durationMs.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      year.hashCode ^
      genre.hashCode ^
      coverPath.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      order.hashCode ^
      isFavorite.hashCode ^
      hasCue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MusicItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          playlistId == other.playlistId &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          filePath == other.filePath &&
          durationMs == other.durationMs &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          year == other.year &&
          genre == other.genre &&
          coverPath == other.coverPath &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          order == other.order &&
          isFavorite == other.isFavorite &&
          hasCue == other.hasCue;
}

class PlayRecordInfo {
  final String id;
  final String musicId;
  final PlatformInt64 playedAt;
  final int playCount;

  const PlayRecordInfo({
    required this.id,
    required this.musicId,
    required this.playedAt,
    required this.playCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ musicId.hashCode ^ playedAt.hashCode ^ playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayRecordInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          musicId == other.musicId &&
          playedAt == other.playedAt &&
          playCount == other.playCount;
}

class Playlist {
  final String id;
  final String name;
  final String? coverPath;
  final BigInt itemCount;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final bool isDefault;

  /// 所属目录 ID，null 表示根级
  final String? folderId;

  const Playlist({
    required this.id,
    required this.name,
    this.coverPath,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
    required this.isDefault,
    this.folderId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      coverPath.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      isDefault.hashCode ^
      folderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          coverPath == other.coverPath &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          isDefault == other.isDefault &&
          folderId == other.folderId;
}

/// 路径映射节点类型
enum PathMappingNodeType {
  directory,
  audioFile,
  imageFile,
  cueFile,
  otherFile,
}

/// 路径映射节点（树形结构，映射磁盘路径）
class PathMappingNodeInfo {
  /// 节点名称
  final String name;

  /// 完整路径
  final String path;

  /// 节点类型
  final PathMappingNodeType nodeType;

  /// 文件大小（字节），仅文件有效
  final int? fileSize;

  /// 子节点
  final List<PathMappingNodeInfo> children;

  /// 是否包含音频文件（文件夹属性，递归检查）
  final bool hasAudio;

  /// 所属文件夹 ID（null 表示根级）
  final String? folderId;

  const PathMappingNodeInfo({
    required this.name,
    required this.path,
    required this.nodeType,
    this.fileSize,
    required this.children,
    required this.hasAudio,
    this.folderId,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      nodeType.hashCode ^
      fileSize.hashCode ^
      children.hashCode ^
      hasAudio.hashCode ^
      folderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathMappingNodeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          nodeType == other.nodeType &&
          fileSize == other.fileSize &&
          children == other.children &&
          hasAudio == other.hasAudio &&
          folderId == other.folderId;
}
