// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_chapter`, `convert_content`, `convert_metadata`, `convert_search_match`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 扫描文件夹获取小说列表
List<NovelMetadata> scanNovelsFolder({required String folderPath}) => RustLib
    .instance
    .api
    .crateApiNovelReaderScanNovelsFolder(folderPath: folderPath);

/// 获取所有小说列表
List<NovelMetadata> getAllNovels() =>
    RustLib.instance.api.crateApiNovelReaderGetAllNovels();

/// 添加单个小说
NovelMetadata addNovel({required String filePath}) =>
    RustLib.instance.api.crateApiNovelReaderAddNovel(filePath: filePath);

/// 从库中移除小说
void removeNovel({required String novelId}) =>
    RustLib.instance.api.crateApiNovelReaderRemoveNovel(novelId: novelId);

/// 获取小说的完整内容（包含所有章节）
Future<NovelContent> getNovelContent({required String filePath}) =>
    RustLib.instance.api.crateApiNovelReaderGetNovelContent(filePath: filePath);

/// 获取特定章节的内容
Future<String> getChapterContent({
  required String filePath,
  required BigInt chapterIndex,
}) => RustLib.instance.api.crateApiNovelReaderGetChapterContent(
  filePath: filePath,
  chapterIndex: chapterIndex,
);

/// 在小说中搜索关键词
Future<List<SearchMatch>> searchInNovel({
  required String filePath,
  required String keyword,
}) => RustLib.instance.api.crateApiNovelReaderSearchInNovel(
  filePath: filePath,
  keyword: keyword,
);

/// 更新阅读进度
void updateReadingProgress({
  required String novelId,
  required double progress,
}) => RustLib.instance.api.crateApiNovelReaderUpdateReadingProgress(
  novelId: novelId,
  progress: progress,
);

class NovelChapter {
  final String id;
  final String title;
  final BigInt index;
  final String? content;

  const NovelChapter({
    required this.id,
    required this.title,
    required this.index,
    this.content,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ index.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelChapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          index == other.index &&
          content == other.content;
}

class NovelContent {
  final String novelId;
  final List<NovelChapter> chapters;

  const NovelContent({required this.novelId, required this.chapters});

  @override
  int get hashCode => novelId.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelContent &&
          runtimeType == other.runtimeType &&
          novelId == other.novelId &&
          chapters == other.chapters;
}

enum NovelFormat { txt, epub }

class NovelMetadata {
  final String id;
  final String title;
  final String? author;
  final String filePath;
  final NovelFormat format;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final PlatformInt64 addedAt;
  final double progress;
  final PlatformInt64? lastReadAt;
  final String? coverPath;

  const NovelMetadata({
    required this.id,
    required this.title,
    this.author,
    required this.filePath,
    required this.format,
    required this.fileSize,
    required this.modifiedAt,
    required this.addedAt,
    required this.progress,
    this.lastReadAt,
    this.coverPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      filePath.hashCode ^
      format.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      addedAt.hashCode ^
      progress.hashCode ^
      lastReadAt.hashCode ^
      coverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          filePath == other.filePath &&
          format == other.format &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          addedAt == other.addedAt &&
          progress == other.progress &&
          lastReadAt == other.lastReadAt &&
          coverPath == other.coverPath;
}

class SearchMatch {
  final BigInt chapterIndex;
  final String chapterTitle;
  final BigInt position;
  final String snippet;

  const SearchMatch({
    required this.chapterIndex,
    required this.chapterTitle,
    required this.position,
    required this.snippet,
  });

  @override
  int get hashCode =>
      chapterIndex.hashCode ^
      chapterTitle.hashCode ^
      position.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchMatch &&
          runtimeType == other.runtimeType &&
          chapterIndex == other.chapterIndex &&
          chapterTitle == other.chapterTitle &&
          position == other.position &&
          snippet == other.snippet;
}
