// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_chapter`, `convert_content`, `convert_folder`, `convert_metadata`, `convert_scan_batch_result`, `convert_search_batch_result`, `convert_search_match`, `convert_search_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 扫描文件夹获取书籍列表
List<NovelMetadata> scanNovelsFolder({required String folderPath}) =>
    RustLib.instance.api.crateApiNovelReaderScanNovelsFolder(folderPath: folderPath);

/// 获取所有书籍列表
List<NovelMetadata> getAllNovels() => RustLib.instance.api.crateApiNovelReaderGetAllNovels();

/// 添加书籍（支持单个路径或多路径）
List<NovelMetadata> addNovel({required List<String> filePaths}) =>
    RustLib.instance.api.crateApiNovelReaderAddNovel(filePaths: filePaths);

/// 从库中移除书籍
void removeNovel({required String novelId}) =>
    RustLib.instance.api.crateApiNovelReaderRemoveNovel(novelId: novelId);

/// 从库中移除书籍及其文件
void removeNovelWithFile({required String novelId}) =>
    RustLib.instance.api.crateApiNovelReaderRemoveNovelWithFile(novelId: novelId);

/// 清空所有书籍
void clearAllNovels() => RustLib.instance.api.crateApiNovelReaderClearAllNovels();

/// 获取书籍的完整内容（包含所有章节）
Future<NovelContent> getNovelContent({required String filePath}) =>
    RustLib.instance.api.crateApiNovelReaderGetNovelContent(filePath: filePath);

/// 获取特定章节的内容
Future<String> getChapterContent({required String filePath, required BigInt chapterIndex}) =>
    RustLib.instance.api.crateApiNovelReaderGetChapterContent(
      filePath: filePath,
      chapterIndex: chapterIndex,
    );

/// 在书籍中搜索关键词
Future<List<SearchMatch>> searchInNovel({required String filePath, required String keyword}) =>
    RustLib.instance.api.crateApiNovelReaderSearchInNovel(filePath: filePath, keyword: keyword);

/// 更新阅读进度
void updateReadingProgress({required String novelId, required double progress}) => RustLib
    .instance
    .api
    .crateApiNovelReaderUpdateReadingProgress(novelId: novelId, progress: progress);

/// 创建文件夹
NovelFolder createNovelFolder({required String name}) =>
    RustLib.instance.api.crateApiNovelReaderCreateFolder(name: name);

/// 获取所有文件夹
List<NovelFolder> getAllNovelFolders() => RustLib.instance.api.crateApiNovelReaderGetAllFolders();

/// 删除文件夹
void deleteFolder({required String folderId}) =>
    RustLib.instance.api.crateApiNovelReaderDeleteFolder(folderId: folderId);

/// 移动书籍到文件夹
void moveNovelToFolder({required String novelId, String? folderId}) =>
    RustLib.instance.api.crateApiNovelReaderMoveNovelToFolder(novelId: novelId, folderId: folderId);

/// 更新书籍排序
void updateNovelOrder({required String novelId, required int order}) =>
    RustLib.instance.api.crateApiNovelReaderUpdateNovelOrder(novelId: novelId, order: order);

/// 批量更新书籍排序
void batchUpdateNovelOrders({required List<String> novelIds}) =>
    RustLib.instance.api.crateApiNovelReaderBatchUpdateNovelOrders(novelIds: novelIds);

/// 取消搜索
void cancelSearch() => RustLib.instance.api.crateApiNovelReaderCancelSearch();

/// 在所有书籍中搜索关键词（批量搜索，支持进度反馈和取消）
Future<List<SearchBatchResult>> searchInAllNovelsBatched({
  required String keyword,
  required BigInt batchSize,
}) => RustLib.instance.api.crateApiNovelReaderSearchInAllNovelsBatched(
  keyword: keyword,
  batchSize: batchSize,
);

/// 在所有书籍中搜索关键词（批量搜索，性能优化）
Future<List<NovelSearchResult>> searchInAllNovels({required String keyword}) =>
    RustLib.instance.api.crateApiNovelReaderSearchInAllNovels(keyword: keyword);

/// 批量扫描文件夹（分批返回结果，避免阻塞）
Future<List<ScanBatchResult>> scanNovelsFolderBatched({
  required String folderPath,
  required BigInt batchSize,
}) => RustLib.instance.api.crateApiNovelReaderScanNovelsFolderBatched(
  folderPath: folderPath,
  batchSize: batchSize,
);

class NovelChapter {
  final String id;
  final String title;
  final BigInt index;
  final String? content;

  const NovelChapter({required this.id, required this.title, required this.index, this.content});

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ index.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelChapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          index == other.index &&
          content == other.content;
}

class NovelContent {
  final String novelId;
  final List<NovelChapter> chapters;

  const NovelContent({required this.novelId, required this.chapters});

  @override
  int get hashCode => novelId.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelContent &&
          runtimeType == other.runtimeType &&
          novelId == other.novelId &&
          chapters == other.chapters;
}

class NovelFolder {
  final String id;
  final String name;
  final PlatformInt64 createdAt;
  final int order;

  const NovelFolder({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.order,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ createdAt.hashCode ^ order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelFolder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          order == other.order;
}

enum NovelFormat { txt, epub }

class NovelMetadata {
  final String id;
  final String title;
  final String? author;
  final String filePath;
  final NovelFormat format;
  final BigInt fileSize;
  final PlatformInt64 modifiedAt;
  final PlatformInt64 addedAt;
  final double progress;
  final PlatformInt64? lastReadAt;
  final String? coverPath;
  final String? folderId;
  final int? customOrder;

  const NovelMetadata({
    required this.id,
    required this.title,
    this.author,
    required this.filePath,
    required this.format,
    required this.fileSize,
    required this.modifiedAt,
    required this.addedAt,
    required this.progress,
    this.lastReadAt,
    this.coverPath,
    this.folderId,
    this.customOrder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      filePath.hashCode ^
      format.hashCode ^
      fileSize.hashCode ^
      modifiedAt.hashCode ^
      addedAt.hashCode ^
      progress.hashCode ^
      lastReadAt.hashCode ^
      coverPath.hashCode ^
      folderId.hashCode ^
      customOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          filePath == other.filePath &&
          format == other.format &&
          fileSize == other.fileSize &&
          modifiedAt == other.modifiedAt &&
          addedAt == other.addedAt &&
          progress == other.progress &&
          lastReadAt == other.lastReadAt &&
          coverPath == other.coverPath &&
          folderId == other.folderId &&
          customOrder == other.customOrder;
}

/// 书籍搜索结果
class NovelSearchResult {
  final NovelMetadata novel;
  final BigInt matchCount;

  const NovelSearchResult({required this.novel, required this.matchCount});

  @override
  int get hashCode => novel.hashCode ^ matchCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelSearchResult &&
          runtimeType == other.runtimeType &&
          novel == other.novel &&
          matchCount == other.matchCount;
}

/// 扫描批次结果
class ScanBatchResult {
  final List<NovelMetadata> novels;
  final BigInt completed;
  final BigInt total;
  final bool isFinished;

  const ScanBatchResult({
    required this.novels,
    required this.completed,
    required this.total,
    required this.isFinished,
  });

  @override
  int get hashCode => novels.hashCode ^ completed.hashCode ^ total.hashCode ^ isFinished.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanBatchResult &&
          runtimeType == other.runtimeType &&
          novels == other.novels &&
          completed == other.completed &&
          total == other.total &&
          isFinished == other.isFinished;
}

/// 搜索批次结果
class SearchBatchResult {
  final List<NovelSearchResult> results;
  final BigInt completed;
  final BigInt total;
  final bool isFinished;

  const SearchBatchResult({
    required this.results,
    required this.completed,
    required this.total,
    required this.isFinished,
  });

  @override
  int get hashCode => results.hashCode ^ completed.hashCode ^ total.hashCode ^ isFinished.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchBatchResult &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          completed == other.completed &&
          total == other.total &&
          isFinished == other.isFinished;
}

class SearchMatch {
  final BigInt chapterIndex;
  final String chapterTitle;
  final BigInt position;
  final String snippet;

  const SearchMatch({
    required this.chapterIndex,
    required this.chapterTitle,
    required this.position,
    required this.snippet,
  });

  @override
  int get hashCode =>
      chapterIndex.hashCode ^ chapterTitle.hashCode ^ position.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchMatch &&
          runtimeType == other.runtimeType &&
          chapterIndex == other.chapterIndex &&
          chapterTitle == other.chapterTitle &&
          position == other.position &&
          snippet == other.snippet;
}
