// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化 PicACG 客户端
void picacgInit() => RustLib.instance.api.crateApiPicacgPicacgInit();

/// 设置代理
void picacgSetProxy({required String proxyUrl}) =>
    RustLib.instance.api.crateApiPicacgPicacgSetProxy(proxyUrl: proxyUrl);

/// 直接写入 Token
void picacgSetToken({required String token}) =>
    RustLib.instance.api.crateApiPicacgPicacgSetToken(token: token);

/// 获取当前 Token
String picacgGetToken() => RustLib.instance.api.crateApiPicacgPicacgGetToken();

/// 登出并清除 Token
void picacgLogout() => RustLib.instance.api.crateApiPicacgPicacgLogout();

/// 设置 API 分流模式
/// - 0: 标准直连
/// - 2: 分流2 (IP: 104.21.91.145)
/// - 3: 分流3 (IP: 188.114.98.153)
/// - 4: CDN分流 (自定义IP，默认 104.18.227.172)
/// - 5: JP反代 (https://bika-api.jpacg.cc)
/// - 6: US反代 (https://bika2-api.jpacg.cc)
void picacgSetChannel({required int mode, required String custom}) => RustLib
    .instance
    .api
    .crateApiPicacgPicacgSetChannel(mode: mode, custom: custom);

/// 设置图片服务器（如 s3.picacomic.com / storage1.picacomic.com）
void picacgSetImageServer({required String server}) =>
    RustLib.instance.api.crateApiPicacgPicacgSetImageServer(server: server);

/// 获取当前图片服务器
String picacgGetImageServer() =>
    RustLib.instance.api.crateApiPicacgPicacgGetImageServer();

/// 测试分流节点连通性，返回延迟(ms)
Future<BigInt> picacgTestChannel({required int mode, required String custom}) =>
    RustLib.instance.api.crateApiPicacgPicacgTestChannel(
      mode: mode,
      custom: custom,
    );

/// 登录
Future<String> picacgLogin({required String email, required String password}) =>
    RustLib.instance.api.crateApiPicacgPicacgLogin(
      email: email,
      password: password,
    );

/// 获取用户信息
Future<String> picacgGetUserProfile() =>
    RustLib.instance.api.crateApiPicacgPicacgGetUserProfile();

/// 每日签到
Future<String> picacgPunchIn() =>
    RustLib.instance.api.crateApiPicacgPicacgPunchIn();

/// 获取首页精选推荐
Future<String> picacgGetCollections() =>
    RustLib.instance.api.crateApiPicacgPicacgGetCollections();

/// 获取随机漫画
Future<String> picacgGetRandomComics() =>
    RustLib.instance.api.crateApiPicacgPicacgGetRandomComics();

/// 获取所有分类
Future<String> picacgGetCategories() =>
    RustLib.instance.api.crateApiPicacgPicacgGetCategories();

/// 按分类获取漫画列表
Future<String> picacgGetComicsByCategory({
  required String category,
  required int page,
  required String sort,
}) => RustLib.instance.api.crateApiPicacgPicacgGetComicsByCategory(
  category: category,
  page: page,
  sort: sort,
);

/// 高级搜索
Future<String> picacgSearchComics({
  required String keyword,
  required List<String> categories,
  required int page,
  required String sort,
}) => RustLib.instance.api.crateApiPicacgPicacgSearchComics(
  keyword: keyword,
  categories: categories,
  page: page,
  sort: sort,
);

/// 热门搜索关键词
Future<String> picacgGetKeywords() =>
    RustLib.instance.api.crateApiPicacgPicacgGetKeywords();

/// 排行榜
Future<String> picacgGetRankings({required String timeType}) =>
    RustLib.instance.api.crateApiPicacgPicacgGetRankings(timeType: timeType);

/// 漫画详情
Future<String> picacgGetComicDetail({required String comicId}) =>
    RustLib.instance.api.crateApiPicacgPicacgGetComicDetail(comicId: comicId);

/// 漫画相关推荐
Future<String> picacgGetComicRecommendations({required String comicId}) =>
    RustLib.instance.api.crateApiPicacgPicacgGetComicRecommendations(
      comicId: comicId,
    );

/// 章节列表
Future<String> picacgGetComicEps({
  required String comicId,
  required int page,
}) => RustLib.instance.api.crateApiPicacgPicacgGetComicEps(
  comicId: comicId,
  page: page,
);

/// 章节图片
Future<String> picacgGetEpsPages({
  required String comicId,
  required int epsOrder,
  required int page,
}) => RustLib.instance.api.crateApiPicacgPicacgGetEpsPages(
  comicId: comicId,
  epsOrder: epsOrder,
  page: page,
);

/// 收藏列表
Future<String> picacgGetFavourites({required int page, required String sort}) =>
    RustLib.instance.api.crateApiPicacgPicacgGetFavourites(
      page: page,
      sort: sort,
    );

/// 切换收藏状态
Future<String> picacgToggleFavourite({required String comicId}) =>
    RustLib.instance.api.crateApiPicacgPicacgToggleFavourite(comicId: comicId);

/// 切换点赞状态
Future<String> picacgToggleLike({required String comicId}) =>
    RustLib.instance.api.crateApiPicacgPicacgToggleLike(comicId: comicId);

/// 评论列表
Future<String> picacgGetComments({
  required String comicId,
  required int page,
}) => RustLib.instance.api.crateApiPicacgPicacgGetComments(
  comicId: comicId,
  page: page,
);

/// 子评论列表
Future<String> picacgGetCommentChildren({
  required String commentId,
  required int page,
}) => RustLib.instance.api.crateApiPicacgPicacgGetCommentChildren(
  commentId: commentId,
  page: page,
);

/// 发表评论
Future<String> picacgSendComment({
  required String comicId,
  required String content,
}) => RustLib.instance.api.crateApiPicacgPicacgSendComment(
  comicId: comicId,
  content: content,
);

/// 点赞评论
Future<String> picacgLikeComment({required String commentId}) =>
    RustLib.instance.api.crateApiPicacgPicacgLikeComment(commentId: commentId);

/// 构建完整图片 URL
String picacgBuildImageUrl({
  required String fileServer,
  required String path,
}) => RustLib.instance.api.crateApiPicacgPicacgBuildImageUrl(
  fileServer: fileServer,
  path: path,
);

Future<Uint8List> picacgFetchImage({
  required String fileServer,
  required String path,
}) => RustLib.instance.api.crateApiPicacgPicacgFetchImage(
  fileServer: fileServer,
  path: path,
);
