// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String powerStatsInit({required String configJson}) => RustLib.instance.api
    .crateApiPowerStatsPowerStatsInit(configJson: configJson);

void powerStatsUpdateConfig({required String configJson}) => RustLib
    .instance
    .api
    .crateApiPowerStatsPowerStatsUpdateConfig(configJson: configJson);

String powerStatsGetConfig() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsGetConfig();

void powerStatsSetEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiPowerStatsPowerStatsSetEnabled(enabled: enabled);

Future<String> powerStatsFetchOnce() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsFetchOnce();

Future<void> powerStatsStartPolling() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsStartPolling();

Future<void> powerStatsStopPolling() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsStopPolling();

String powerStatsGetStatus() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsGetStatus();

String powerStatsGetAggregated({required String range}) => RustLib.instance.api
    .crateApiPowerStatsPowerStatsGetAggregated(range: range);

String powerStatsGetSummary() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsGetSummary();

String powerStatsGetLogs() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsGetLogs();

void powerStatsClearLogs() =>
    RustLib.instance.api.crateApiPowerStatsPowerStatsClearLogs();
