// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化Sentry日志存储
String sentryLogInit({required String dbPath}) =>
    RustLib.instance.api.crateApiSentryLogSentryLogInit(dbPath: dbPath);

/// 查询Sentry日志事件
Future<String> sentryLogQuery({
  String? projectId,
  String? level,
  String? query,
  String? environment,
  String? startTime,
  String? endTime,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiSentryLogSentryLogQuery(
  projectId: projectId,
  level: level,
  query: query,
  environment: environment,
  startTime: startTime,
  endTime: endTime,
  offset: offset,
  limit: limit,
);

/// 获取单个Sentry事件
Future<String> sentryLogGetEvent({required String eventId}) =>
    RustLib.instance.api.crateApiSentryLogSentryLogGetEvent(eventId: eventId);

/// 删除Sentry事件
Future<bool> sentryLogDeleteEvent({required String eventId}) => RustLib
    .instance
    .api
    .crateApiSentryLogSentryLogDeleteEvent(eventId: eventId);

/// 批量删除Sentry事件
Future<BigInt> sentryLogDeleteEvents({required List<String> eventIds}) =>
    RustLib.instance.api.crateApiSentryLogSentryLogDeleteEvents(
      eventIds: eventIds,
    );

/// 获取Sentry项目列表
Future<String> sentryLogGetProjects() =>
    RustLib.instance.api.crateApiSentryLogSentryLogGetProjects();

/// 更新Sentry项目名称
Future<void> sentryLogUpdateProjectName({
  required String projectId,
  required String name,
}) => RustLib.instance.api.crateApiSentryLogSentryLogUpdateProjectName(
  projectId: projectId,
  name: name,
);

/// 获取Sentry日志统计
Future<String> sentryLogGetStats() =>
    RustLib.instance.api.crateApiSentryLogSentryLogGetStats();

/// 导出Sentry日志为JSON
Future<String> sentryLogExportJson({
  String? projectId,
  String? level,
  String? query,
  String? environment,
  String? startTime,
  String? endTime,
}) => RustLib.instance.api.crateApiSentryLogSentryLogExportJson(
  projectId: projectId,
  level: level,
  query: query,
  environment: environment,
  startTime: startTime,
  endTime: endTime,
);

/// 清空项目事件
Future<BigInt> sentryLogClearProjectEvents({required String projectId}) =>
    RustLib.instance.api.crateApiSentryLogSentryLogClearProjectEvents(
      projectId: projectId,
    );
