// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `metrics_system`, `net_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NetSpeedState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

SystemResourceSnapshot getSystemResourceSnapshot() =>
    RustLib.instance.api.crateApiSystemMetricsGetSystemResourceSnapshot();

class SystemResourceSnapshot {
  final double cpuUsagePercent;
  final BigInt memoryUsedMb;
  final BigInt memoryTotalMb;
  final double rxKbps;
  final double txKbps;

  const SystemResourceSnapshot({
    required this.cpuUsagePercent,
    required this.memoryUsedMb,
    required this.memoryTotalMb,
    required this.rxKbps,
    required this.txKbps,
  });

  @override
  int get hashCode =>
      cpuUsagePercent.hashCode ^
      memoryUsedMb.hashCode ^
      memoryTotalMb.hashCode ^
      rxKbps.hashCode ^
      txKbps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemResourceSnapshot &&
          runtimeType == other.runtimeType &&
          cpuUsagePercent == other.cpuUsagePercent &&
          memoryUsedMb == other.memoryUsedMb &&
          memoryTotalMb == other.memoryTotalMb &&
          rxKbps == other.rxKbps &&
          txKbps == other.txKbps;
}
