// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 创建 WebSocket 客户端
WsClient wsClientNew({required String url}) =>
    RustLib.instance.api.crateApiWebsocketWsClientNew(url: url);

/// 连接到 WebSocket 服务器
Future<void> wsClientConnect({required WsClient client}) =>
    RustLib.instance.api.crateApiWebsocketWsClientConnect(client: client);

/// 断开连接
Future<void> wsClientDisconnect({required WsClient client}) =>
    RustLib.instance.api.crateApiWebsocketWsClientDisconnect(client: client);

/// 发送文本消息
Future<void> wsClientSendText({
  required WsClient client,
  required String message,
}) => RustLib.instance.api.crateApiWebsocketWsClientSendText(
  client: client,
  message: message,
);

/// 发送二进制消息
Future<void> wsClientSendBinary({
  required WsClient client,
  required List<int> data,
}) => RustLib.instance.api.crateApiWebsocketWsClientSendBinary(
  client: client,
  data: data,
);

/// 检查是否已连接
Future<bool> wsClientIsConnected({required WsClient client}) =>
    RustLib.instance.api.crateApiWebsocketWsClientIsConnected(client: client);

/// 获取连接状态
Future<WsConnectionState> wsClientGetState({required WsClient client}) =>
    RustLib.instance.api.crateApiWebsocketWsClientGetState(client: client);

/// 接收消息（非阻塞）
Future<WsMessage?> wsClientReceiveMessage({required WsClient client}) => RustLib
    .instance
    .api
    .crateApiWebsocketWsClientReceiveMessage(client: client);

/// 获取消息数据
String wsMessageGetData({required WsMessage message}) =>
    RustLib.instance.api.crateApiWebsocketWsMessageGetData(message: message);

/// 获取消息时间戳
PlatformInt64 wsMessageGetTimestamp({required WsMessage message}) => RustLib
    .instance
    .api
    .crateApiWebsocketWsMessageGetTimestamp(message: message);

/// 检查是否为文本消息
bool wsMessageIsText({required WsMessage message}) =>
    RustLib.instance.api.crateApiWebsocketWsMessageIsText(message: message);

/// 检查是否为二进制消息
bool wsMessageIsBinary({required WsMessage message}) =>
    RustLib.instance.api.crateApiWebsocketWsMessageIsBinary(message: message);

WsServer wsServerNew({required String host, required int port}) =>
    RustLib.instance.api.crateApiWebsocketWsServerNew(host: host, port: port);

Future<void> wsServerStart({required WsServer server}) =>
    RustLib.instance.api.crateApiWebsocketWsServerStart(server: server);

Future<void> wsServerStop({required WsServer server}) =>
    RustLib.instance.api.crateApiWebsocketWsServerStop(server: server);

Future<void> wsServerBroadcast({
  required WsServer server,
  required String message,
}) => RustLib.instance.api.crateApiWebsocketWsServerBroadcast(
  server: server,
  message: message,
);

Future<BigInt> wsServerGetClientCount({required WsServer server}) => RustLib
    .instance
    .api
    .crateApiWebsocketWsServerGetClientCount(server: server);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WsClient>>
abstract class WsClient implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WsConnectionState>>
abstract class WsConnectionState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WsMessage>>
abstract class WsMessage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WsServer>>
abstract class WsServer implements RustOpaqueInterface {}
