// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_result`, `convert_segment`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// 初始化 whisper 配置
void whisperInitialize() =>
    RustLib.instance.api.crateApiWhisperWhisperInitialize();

/// 获取所有可用模型的状态
List<ModelStatusInfo> whisperGetModelStatuses() =>
    RustLib.instance.api.crateApiWhisperWhisperGetModelStatuses();

/// 获取当前选中的模型名称
String whisperGetSelectedModel() =>
    RustLib.instance.api.crateApiWhisperWhisperGetSelectedModel();

/// 设置当前选中的模型
bool whisperSetSelectedModel({required String presetName}) => RustLib
    .instance
    .api
    .crateApiWhisperWhisperSetSelectedModel(presetName: presetName);

/// 下载指定模型（阻塞，建议在后台调用）
Future<BigInt> whisperDownloadModel({required String presetName}) => RustLib
    .instance
    .api
    .crateApiWhisperWhisperDownloadModel(presetName: presetName);

/// 删除指定模型
bool whisperDeleteModel({required String presetName}) => RustLib.instance.api
    .crateApiWhisperWhisperDeleteModel(presetName: presetName);

/// 识别音频文件并生成 CUE 文件
/// 返回识别结果（包含片段和完整文本），同时生成 .cue 文件在音频同级目录
Future<TranscriptionResultInfo> whisperTranscribe({
  required String audioFilePath,
  String? language,
}) => RustLib.instance.api.crateApiWhisperWhisperTranscribe(
  audioFilePath: audioFilePath,
  language: language,
);

/// 模型状态信息
class ModelStatusInfo {
  final String presetName;
  final String displayName;
  final bool modelFileExists;
  final String? modelFilePath;
  final BigInt? modelFileSize;
  final BigInt approximateSizeMb;

  const ModelStatusInfo({
    required this.presetName,
    required this.displayName,
    required this.modelFileExists,
    this.modelFilePath,
    this.modelFileSize,
    required this.approximateSizeMb,
  });

  @override
  int get hashCode =>
      presetName.hashCode ^
      displayName.hashCode ^
      modelFileExists.hashCode ^
      modelFilePath.hashCode ^
      modelFileSize.hashCode ^
      approximateSizeMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelStatusInfo &&
          runtimeType == other.runtimeType &&
          presetName == other.presetName &&
          displayName == other.displayName &&
          modelFileExists == other.modelFileExists &&
          modelFilePath == other.modelFilePath &&
          modelFileSize == other.modelFileSize &&
          approximateSizeMb == other.approximateSizeMb;
}

/// 识别结果
class TranscriptionResultInfo {
  final String language;
  final List<TranscriptionSegmentInfo> segments;
  final String fullText;

  const TranscriptionResultInfo({
    required this.language,
    required this.segments,
    required this.fullText,
  });

  @override
  int get hashCode => language.hashCode ^ segments.hashCode ^ fullText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionResultInfo &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          segments == other.segments &&
          fullText == other.fullText;
}

/// 识别片段
class TranscriptionSegmentInfo {
  final BigInt startMs;
  final BigInt endMs;
  final String text;

  const TranscriptionSegmentInfo({
    required this.startMs,
    required this.endMs,
    required this.text,
  });

  @override
  int get hashCode => startMs.hashCode ^ endMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionSegmentInfo &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text;
}
